% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[referee,pdflatex,sn-basic]{sn-jnl}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{xcolor}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{longtable}
\usepackage{booktabs}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}

% sn-jnl wraps every table float in threeparttable. The manuscript tables are
% generated by kableExtra, which already supplies that environment and may put
% it inside resizebox. Restore the original float environments saved by the
% class to avoid an illegal nested threeparttable while preserving Springer
% typography elsewhere.
\makeatletter
\renewenvironment{table}[1][]{\tableorg[#1]}{\endtableorg\normalfont}
\renewenvironment{sidewaystable}[1][]{\sidewaystableorg[#1]}{\endsidewaystableorg\normalfont}
\makeatother

\setcounter{secnumdepth}{3}

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\theoremstyle{thmstylethree}
\newtheorem{modelproposition}{Proposition}
\newtheorem{modelcorollary}{Corollary}
\newtheorem{modellemma}{Lemma}
\let\proposition\modelproposition
\let\endproposition\endmodelproposition
\let\corollary\modelcorollary
\let\endcorollary\endmodelcorollary
\let\lemma\modellemma
\let\endlemma\endmodellemma
\newcommand{\pospart}[1]{\left[#1\right]_{+}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={The Foreign Policy Impact of Trade-Based Status Gains: When China Overtakes the US as Top Export Destination},
  pdfkeywords={China, foreign policy alignment, international political economy, trade-based status, synthetic difference-in-differences, United Nations General Assembly},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

% Keep paragraph spacing stable in the double-spaced referee layout. The
% Springer class's flush-bottom setting can otherwise stretch vertical glue
% dramatically on pages with floats or short final paragraphs.
\setlength{\parindent}{1.5em}
\setlength{\parskip}{0pt}
\raggedbottom

\begin{document}

\title[Trade-Based Status Gains and Foreign Policy]{The Foreign Policy Impact of Trade-Based Status Gains: When China Overtakes the US as Top Export Destination}

% Author information intentionally omitted for double-anonymous review.

\abstract{\begin{singlespace}\textbf{Purpose:} How do countries adjust their foreign policy when a rising power becomes their leading trading partner?\\
\textbf{Methods:} I develop a formal model in which public recognition increases the salience of a new trade rank, and political leadership's cost-benefit analysis of foreign-policy alignment with the rising power determines its direction of change. To test the hypothesis derived from the model, I leverage the timing of China's surpassing the United States as Brazil's largest export destination and fit a synthetic difference-in-differences model to estimate the effect of the status change on Brazil's voting at the United Nations General Assembly. To assess whether the pattern extends beyond Brazil, I estimate a latent factor model using a cross-country panel for 2000-2022.\\
\textbf{Results:} Brazilian policymakers invoked China's new position to justify greater proximity between the countries, with voting convergence particularly visible on human rights issues. Relative to the counterfactual, the estimated reduction in bilateral voting distance is equivalent to 42 percent of the pre-treatment mean distance. The cross-country results are mixed, but interpreted as consistent with the model.\\
\textbf{Conclusion:} Publicly acknowledged changes in economic rank can support diplomatic adjustments in multilateral institutions, with implications for U.S.-China rivalry as their relative commercial positions change.\end{singlespace}}

\keywords{China, foreign policy alignment, international political economy, trade-based status, synthetic difference-in-differences, United Nations General Assembly}

\maketitle



\pagebreak

\section{Introduction}\label{introduction}

``China overtakes US as Brazil's top trade partner.'' That was a headline in many Brazilian newspapers in 2009 \citep{rodrigues2009}. The BBC ran a similar headline in 2021, when China surpassed the United States as the EU's biggest trading partner \citep{bbc2021}. During a high-profile trip to Beijing with an unusually large business delegation, President Lula da Silva invoked the milestone by noting that China was Brazil's largest export destination \citep{lula2009}.

Export statistics are updated monthly, and international trade journalists, diplomats, and policymakers follow them closely, so there is no new information being transmitted when one partner moves up the ladder of trade hierarchy. And yet, public discourse revolves around such categorical milestones. Why can a milestone, such as China becoming the number-one trade partner, matter politically despite adding little new information about the economic trend itself?

If everyone is perfectly rational, redundant information should not matter. Most of the literature on the effects of interdependence implicitly or explicitly assumes this hyperrationalist perspective and studies how trade and other economic ties shape foreign policy \citep{flores-macias_kreps2013, urdinez_etal2016, kastner_pearson2021}. Therefore, foreign-policy alignment should move gradually with trade exposure and economic interdependence in general. There is no expectation that discrete changes in economic or trade status will produce any effect on the foreign policy of countries.

Domestic political accounts of foreign policy, on the other hand, can conceivably attribute foreign-policy change to discrete changes, but only to changes such as new leadership ideology or political coalition \citep{neto2011, neto_malamud2015, rodrigues2019measuring, schenoniMythsMultipolaritySources2022}.

A different concern for the study of the effect of status change is reverse causality, since politically aligned countries may deepen economic ties with one another, making China's rise in the trade hierarchy a consequence rather than a cause of prior diplomatic affinity \citep{gowa1995, davis_pratt2021, struver2016}. If alignment reflects only accumulated exposure, domestic political reorientation, or prior diplomatic affinity, however, no specific symbolic milestone, such as becoming a top trade partner, should matter.

I argue that such milestones matter because they mark trade-based status gains. The argument builds on research that treats status as socially recognized standing within international hierarchies, clubs, and local status orders \citep{paul_larson_wohlforth2014, wolfRespectDisrespect2011, duque_2018, renshon2017, gotz_2021, roren_2024, roren2025_power_recognition, wolfTakingInteractionSeriously2019}. By trade-based status, I mean the recognized standing of a foreign power within a country's hierarchy of economically consequential relationships. Trade volume is continuous, but status is categorical: a partner can move from being important to being understood as central. Once that reclassification becomes public, the relationship is no longer merely larger than before. It becomes easier for political actors to invoke as a national priority, to defend as strategically consequential, and to use as a justification for diplomatic adjustment.

Much of the China and rising-powers branch of this literature asks how rising states seek recognition, major-power status, or institutional standing, and how misrecognition can produce contestation or revisionism \citep{deng2008_status, larson_shevchenko2010_status_seekers, ward2017_status_challenge, murray2018_recognition, mukherjee2022_ascending}. This argument relocates status from the ambitions of the rising power to the recognition practices of states. China's trade-based status gain occurs when another country publicly recategorizes China within its own hierarchy of external economic relationships -- from an important partner to a central one.

The argument links US-China competition to the recognition practices of third countries. When China overtakes the United States in a national trade hierarchy, its commercial rise can become a public basis for selective diplomatic accommodation. Multilateral voting provides an arena in which countries such as Brazil can adjust their positions toward China while retaining flexibility in other areas of foreign policy. This perspective locates one possible consequence of China's rise for the US-led international order in changes in diplomatic support within existing institutions.

I formalize the argument using a model with two players: political leadership and bureaucracy. The former chooses the foreign policy directive, and the latter decides to implements it. The leadership has sparse attention, and a public cue increases salience; as a result, it increases the weight of the costs and benefits of aligning with the emerging power. The model shows that the public cue is necessary for the new status to have an effect and that foreign policy change also depends on the ideological dispositions of political leadership.

Brazil is the strongest case for the theory. First, China displaced the United States, a politically salient incumbent, hegemonic benchmark, and the most important trade partner of Brazil for almost 80 years. Second, the rank reversal was publicly visible. Third, the Brazilian press allows the attention implication to be measured. The case is also substantively important because Lula-era Brazilian foreign policy is often described through autonomy, South-South activism, multipolarity, and Brazil's triangular position between the United States and China \citep{neto2011, neto_malamud2015, rodrigues2019measuring, schenoniMythsMultipolaritySources2022, guilhon2014, schenoni_leiva2021, brun_covarrubias2024, coutinho_rodriguez2024}.

To estimate the Brazilian foreign-policy alignment pattern, I use Synthetic Difference-in-Differences (SDiD) on annual UNGA ideal-point distance to China, with 2009 marking China's rise to the largest Brazilian export destination. UNGA voting is a standard measure to study alignment with China and other powers, linking votes to bilateral ties, ideology, sanctions, aid, Belt and Road membership, arms transfers, or Chinese economic returns \citep{potrafke2009, dreher_jensen2013, struver2016, yan_zhou2021, garcia_herrero_etal2024, steinert_weyrauch2024, he_zheng_chen2025, lektzian_biglaiser2023}.

In the preferred specification, the estimated reduced-form effect of when China became Brazil's largest export destination is a reduction of 0.273 ideal-point units in Brazil's distance to China relative to its synthetic counterfactual, equivalent to 42.2 percent of its pre-treatment mean, with a one-sided placebo-rank p-value of 0.031.

To assess whether a compatible directional pattern appears beyond Brazil and to check the narrower threat posed by explanations tied specifically to Brazil's 2009 calendar year, I extend the analysis to a cross-country panel in which China enters and holds the top goods-export destination position. The cross-country estimates are smaller in magnitude, consistent with a more heterogeneous sample, and point in the same direction as the Brazilian case. The pooled panel estimate is -0.101 (p-value = 0.010) and is stable across duration thresholds and sample restrictions (p-value between 0.003 and 0.019). The panel evidence identifies a directional pattern associated with entry into the goods-only rank condition; the public-status mechanism is measured directly only in the Brazilian case.

The paper's contribution is to show that economic status matters and impacts foreign policy. Existing work usually treats trade exposure as a smooth source of influence. I argue that accumulated trade growth can become politically consequential when it crosses a durable, publicly legible rank threshold. It is particularly likely when a great power, such as China, holds the new status. In the case of Brazil, China's rise to the top export destination position made an already expanding commercial relationship available in public and official language as evidence of China's new centrality. The mechanism evidence shows that the public cue was available and used by policymakers in their political discourse, working as a focal point.

The next section develops the status-threshold argument and derives observable implications. I then present the Brazil SDiD design and timing diagnostics, followed by issue-area and media evidence on the mechanism. The final empirical section evaluates whether durable China-top goods-export status is associated with similar movement in a broader cross-country panel.

\section{Theory and Hypotheses}\label{theory-and-hypotheses}

To explain the proposed mechanism and hypothesis, I present a simple formal model of sparse attention of policymakers \citep{gabaix2014}. I use sparsity to induce a symbolic cue effect that works as a public cue for foreign policy change.

\subsection{A simple model of public status cues}\label{a-simple-model-of-public-status-cues}

I model how political leadership chooses a policy directive and a diplomatic bureaucracy decides whether to implement it following a publicized change at the top of a country's trade ranking. Public recognition raises attention to the relationship and the bureaucracy's benefit from implementation. The leadership's evaluation of the relationship determines the direction of any policy response.

Let \(R\in\{0,1\}\) indicate whether a revisionist power occupies the top position in the relevant trade hierarchy for a given country. Let \(P\in\{0,1\}\) indicate whether that position has become publicly visible, for example, through press coverage using explicit ranking language.

I assume that policymakers' attention is sparse \citep{gabaix2014}. This means that a change in the new power's status competes for attention with other events in the world and does not automatically produce a change in foreign policy. I call the product \(q=RP\in\{0,1\}\) a political cue. It captures a situation in which the emerging power not only attains its new rank but also has that rank explicitly brought to public attention by the media or public officials. Let salience \(s(q)\geq0\) satisfy \(s(1)>s(0)\). In words, becoming the new number one and receiving public recognition makes the emerging power more salient to policymakers, bringing it to their attention. The function \(s(q)\) represents this attention as an exogenous decision weight.

\subsubsection{Valence}\label{valence}

Let:

\begin{itemize}
\tightlist
\item
  \(G\geq0\): the baseline perceived gains from moving closer to the new great power;
\item
  \(D\geq0\): the baseline perceived costs of increased dependence on the emerging power;
\item
  \(\iota\in[-1,1]\): the leadership's ideological orientation toward the emerging power, where
\end{itemize}

\[
\begin{cases}
\iota>0 & \text{indicates a favorable view of the emerging power;}\\
\iota=0 & \text{indicates neutrality;}\\
\iota<0 & \text{indicates an unfavorable view of the emerging power.}
\end{cases}
\]

The quantities \(G\) and \(D\) are evaluated on a common utility scale before ideological weighting. Ideology affects how much importance the leadership assigns to each component. I define the net marginal value of strengthening ties with China as

\[
\theta=(1+\iota)G-(1-\iota)D
      =(G-D)+\iota(G+D).
\]

An ideologically neutral leadership, \(\iota=0\), evaluates the relationship according to \(G-D\). A favorable orientation increases the weight on gains and reduces the weight on dependence costs; an unfavorable orientation does the reverse. Both weights are nonnegative and sum to two. At the endpoints, \(\iota=1\) places zero weight on dependence costs and \(\iota=-1\) places zero weight on gains. Thus ideology operates through the evaluation of the relationship: if \(G=D=0\), then \(\theta=0\) for every ideological orientation.

Positive \(\theta\) makes movement toward China attractive before adjustment costs; negative \(\theta\) favors hedging or distancing. When \(G+D>0\), the evaluation equals zero at \(\iota_0=(D-G)/(G+D)\). For example, with \(G=2\) and \(D=5\), an orientation of \(\iota=0.5\) yields \(\theta=0.5\), whereas \(\iota=-0.5\) yields \(\theta=-6.5\). Whether either evaluation produces an actual policy change also depends on the costs and implementation conditions specified below. The comparison between \(q=0\) and \(q=1\) holds \(G\), \(D\), and \(\iota\) fixed.

\subsubsection{Players, actions, and information}\label{players-actions-and-information}

There are two players:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The political leadership, \(L\), chooses a policy directive \(d\in\mathbb{R}\), measured as a normalized adjustment relative to the existing policy. Positive values indicate movement toward China; negative values indicate hedging or distancing. A directive of \(d=0\) preserves the existing policy.
\item
  The diplomatic bureaucracy, \(B\), observes the directive and chooses \(e\in\{0,1\}\), where \(e=1\) means implementation.
\end{enumerate}

The realized policy is

\[
y=ed.
\]

The baseline model assumes complete information: \(q\), \(G\), \(D\), \(\iota\), the salience and implementation-benefit functions, and the costs are common knowledge.

\subsubsection{Timing and payoffs}\label{timing-and-payoffs}

The game proceeds in the following order:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The leadership chooses the directive \(d\).
\item
  The bureaucracy observes \(d\) and chooses \(e\).
\item
  The policy \(y=ed\) is realized, and payoffs are received.
\end{enumerate}

The leadership values policy changes that move the relationship in its preferred direction, but must weigh that return against the costs of departure from existing policy. Its payoff, normalized to zero when it issues no directive, is

\[
u_L(d,e;q)
=
e\left[s(q)\theta d-\frac{d^2}{2}\right]
-c_L|d|,
\tag{1}
\]

The term \(s(q)\theta d\) captures the perceived return from the direction and extent of an implemented adjustment. For positive salience, movement toward China yields a positive return when \(\theta>0\); when \(\theta<0\), a negative directive yields a positive return by moving away from a relationship the leadership evaluates unfavorably. Salience determines the weight this evaluation receives in the policy decision. A public cue can therefore increase the incentive to act in either direction while leaving the underlying evaluation \(\theta\) unchanged.

The quadratic term \(d^2/2\) captures the increasing marginal cost of larger implemented departures from existing policy, such as the disruption involved in revising established commitments. Its curvature is normalized to one for simplicity. This term limits the preferred extent of adjustment even when the leadership strongly favors a particular direction. The factor \(e\) multiplies both this cost and the directional return because they arise only when the bureaucracy carries out the directive.

By contrast, \(c_L|d|\), with \(c_L>0\), captures the political effort and reputational exposure involved in formulating and defending a directive, whether or not it is implemented. For example, proposing a change in diplomatic voting instructions requires articulating and defending the new position even if the bureaucracy subsequently leaves voting practice unchanged. This cost rises with the size of the proposed departure and applies to both directions. Conditional on implementation, it creates a region of inaction: the leadership issues a nonzero directive only when the initial marginal return \(s(q)|\theta|\) exceeds \(c_L\).

The bureaucracy's payoff, with \(c_B>0\), is

\[
u_B(e,d;q)
=
e\,\mathbf{1}\{d\neq0\}\,[K(q)-c_B],
\tag{2}
\]

The bureaucracy derives no utility from moving closer to China or to the United States, \(K(q)\) represents the benefits of implementing a given policy, and \(c_B\) the costs. When deriving the equilibrium, I also assume that \(K(1)>K(0)\), which means that implementing a public policy generates higher benefits than a policy without a public cue.

\subsubsection{Equilibrium}\label{equilibrium}

The solution concept is subgame-perfect equilibrium, obtained by backward induction.

\modellemma[Bureaucratic response]
For any directive $d\neq0$, the bureaucracy implements if and only if $K(q)>c_B$. In the event of equality, the conservative tie-breaking rule $e=0$ applies.
\endmodellemma

\textit{Proof.} If \(d\neq0\), implementation yields \(K(q)-c_B\), whereas non-implementation yields zero. Comparing the two directly gives the condition. If \(d=0\), there is no policy to implement, and \(e=0\) is adopted. \(\square\)

\modelproposition[Equilibrium with a directionally neutral cue]
The policy outcome in the subgame-perfect equilibrium is

\[
y^*(q)=
\mathbf{1}\{K(q)>c_B\}
\operatorname{sign}(\theta)
\left[s(q)|\theta|-c_L\right]_{+}.
\tag{3}
\]

where $\left[x\right]_{+}=\max\{x,0\}$. The leadership chooses $d^*(q)=y^*(q)$, anticipating the bureaucratic response specified in Lemma 1.

In particular, the cue can change whether a response occurs and how strong it is, but it does not determine its sign.
\endmodelproposition

\textit{Proof.} If \(K(q)\leq c_B\), the bureaucracy does not implement nonzero directives. Since the leadership pays \(c_L|d|\) even for a directive that is not implemented, its optimal choice is \(d=0\), and therefore \(y=0\).

\begin{minipage}{\linewidth}
If $K(q)>c_B$, every nonzero directive is implemented. The leadership solves

\[
\max_d\left\{s(q)\theta d-\frac{d^2}{2}-c_L|d|\right\}.
\]
\end{minipage}

For \(d>0\), the first-order condition is \(d=s(q)\theta-c_L\); this solution is positive only when \(s(q)\theta>c_L\). For \(d<0\), the condition is \(d=s(q)\theta+c_L\); it is negative only when \(s(q)\theta<-c_L\). In all other cases, the subgradient condition is satisfied at \(d=0\). Combining the three regions yields (3). \(\square\)

To complete the earlier example, take \(G=2\), \(D=5\), and \(\iota=0.5\), so \(\theta=0.5\). Let \(s(0)=0.5\), \(s(1)=1\), \(c_L=0.4\), \(K(0)=2\), \(K(1)=3\), and \(c_B=1\). These are hypothetical normalized values without empirical calibration. The bureaucracy would implement a nonzero directive in either state. Before the cue, \(s(0)|\theta|=0.25\leq0.4\), so \(y^*(0)=0\); after the cue, \(s(1)|\theta|=0.5>0.4\), so \(y^*(1)=0.5-0.4=0.1\).

\medskip

\noindent\textbf{Immediate implications.}

\modelcorollary[The cue has no intrinsic valence]
Whenever $y^*(q)\neq0$,

\[
\operatorname{sign}\bigl(y^*(q)\bigr)=\operatorname{sign}(\theta).
\]

A nonzero response moves toward China when $\theta>0$ and away from China when $\theta<0$; the latter may represent hedging or distancing.
\endmodelcorollary

\modelcorollary[Activation through attention or implementation incentives]
The cue activates a previously absent response when both post-cue conditions hold,

\[
K(1)>c_B
\quad\text{and}\quad
s(1)|\theta|>c_L,
\]

and at least one of them failed to hold before the cue:

\[
K(0)\leq c_B
\quad\text{or}\quad
s(0)|\theta|\leq c_L.
\]
\endmodelcorollary

\modelcorollary[Benchmark with unchanged attention and implementation benefits]
For this comparison, relax the strict assumptions $s(1)>s(0)$ and $K(1)>K(0)$ by setting $s(1)=s(0)$ and $K(1)=K(0)$. When the public label changes neither attention nor implementation benefits, the equilibrium policy remains unchanged.
\endmodelcorollary

The general result therefore concerns magnitude:

\[
|y^*(1)|\geq|y^*(0)|
\]

when the cue weakly increases \(s\) and \(K\). The direction depends on \(\theta\).

\subsubsection{Extensions}\label{extensions}

\medskip

\noindent\textbf{Issue-specific costs.}
To capture selective adjustment, let \(c_L=c_{Lk}\) and \(\theta_k=(1+\iota)G_k-(1-\iota)D_k\) for each issue \(k\), where \(G_k\) and \(D_k\) are the baseline gains and dependence costs relevant to that issue. Conditional on implementation being available both before and after the cue, the attention channel activates a previously absent response on issues satisfying

\[
s(0)|\theta_k|\leq c_{Lk}<s(1)|\theta_k|.
\]

Issues with an already active response can also adjust further as salience increases; issues whose costs remain above the post-cue threshold remain unchanged. If the cue instead makes implementation available for the first time, the activation conditions in Corollary 2 apply issue by issue. The composition of the response depends on the distribution of valuations and costs and does not follow automatically from an issue being classified as human rights or belonging to any other substantive area.

\medskip

\noindent\textbf{Persistence and incumbent prominence.}
Let \(\rho\) denote the expected persistence of the new hierarchy and \(h\) the prominence of the displaced partner. A simple extension allows

\[
\frac{\partial s(1;\rho,h)}{\partial\rho}>0,
\qquad
\frac{\partial s(1;\rho,h)}{\partial h}>0,
\]

with analogous relationships for \(K\). A persistent ranking provides a more stable basis for adaptation; displacing a prominent incumbent makes the reclassification more visible. Neither condition determines the valence of \(\theta\). Holding the leadership's evaluation and both players' costs fixed, increases in persistence or incumbent prominence that raise salience and implementation benefits weakly increase the absolute value of the post-cue policy response, subject to the same thresholds.

\subsection{Interpretation}\label{interpretation}

Policymakers must consider many factors when deciding to change foreign policy. These include trade statistics across many countries, GDP growth, shifts in the balance of power, new alliances and trade partnerships, new technologies, domestic politics, and more. A trade-based status shift may draw attention to a potential policy change that otherwise would not occur through smooth growth in economic interdependence. It simplifies complex economic relationships, helps elites coordinate attention \citep{bordalo_etal2022, conlon2023, enke2024, graeber_etal2025}, and serves as a focal point \citep{schelling1960}.

This attribution of symbolic status between two countries is a common feature of foreign policy. Leaders in Canada refer to their country as a middle power \citep{chapnick1999}. Churchill famously called the US-UK relationship a special one \citep{reynolds1985}. Mitterrand used ``couple franco-allemand'' to promote the European Union \citep{krotz_schild2013}. My argument is that trade status works similarly.

The mechanism has two steps. First, media coverage or official recognition of the new status makes China and the bilateral relationship more visible, increasing \(s(q)\). Second, greater attention from policymakers allows them to perceive a greater marginal net benefit, \(s(q)\theta\), of closer ties with the new major trade partner.

\subsection{Hypothesis}\label{hypothesis}

One would think that the main hypothesis would be that a public cue (by the media and/or political leadership) of a new trade status acquired by an emerging power should generate closer alignment toward that partner.

However, as the model makes clear, a public cue of the new status may instead induce a policy response in the opposite direction. A number-one status may create anxiety among political elites and prompt a decision to move further away from China rather than toward the expected alignment, because the perceived costs outweigh the benefits. It depends on the value of \(\iota\) in the model, which measures policymakers' favorability toward a foreign policy closer to China.

As a result, the hypothesis tested in the paper is: All else equal, whenever a political leadership is favorably oriented toward China (\(\iota>0\)), a public cue of a new trade status by an emerging power increases the probability of closer approximation toward that partner.

For Brazil, with a leftist government interested in South-South cooperation, I argue that the assumption of \(\iota>0\) is plausible. For other countries, the paper's assumption that they will view China favorably is plausible (though not certain) until the mid-2010s, when the US-China rivalry was not as intense as it became by the end of the decade.

Since I am estimating a reduced-form model, the mechanism is not estimated directly from the model. As mentioned, an increased public cue may not induce foreign-policy alignment toward China because a new directive also depends on the leadership's ideological leanings toward China. Another important caveat that the cross-country regression makes clear is that, without a public cue, the model predicts no foreign policy change as a result of the new trade status of the emerging power. Without systematic data on the presence or absence of public cues for every country, I may be mixing cases with and without a public cue. Thus, I expect the average effect to be smaller than in the Brazil case.

The model extension also implies a durability condition. The higher the persistence of the new status, the higher the salience, which should increase the likelihood of a foreign policy orientation. A one-year episode of China as the number one trade partner may attract attention, but it is a weaker treatment regime.

Last but not least, trade-based status changes may impact foreign policy issues differently. Some foreign-policy arenas are especially suitable for this kind of adjustment. There are two key conditions: the country and the newly elevated partner previously differed, and the costs of movement are high enough to prevent adjustment before the cue but low enough to be overcome afterward.

\section{Data and Design}\label{data-and-design}

The theoretical concept of interest is the rising power obtaining the status of top trade partner of a country. However, public status language varies in what counts as a top trade partner and in how it is described. Officials and journalists may describe China as the largest trading partner, main commercial partner, or top export market, for instance. Countries also value different things as a matter of status: largest flow of trade (exports plus imports) is what matters for some countries. For others, it is largest total exports (goods and services), or largest goods exports.

For the argument advanced in the article, what matters is the status change. Export-destination rank operationalizes the trade-based status shift. But since I have more information about Brazil than about other countries, I explain the differences in how I operationalize the treatment in the SDiD model and the cross-country panel regression.

\subsection{SDiD Design}\label{sdid-design}

In the design in which Brazil is the only treated country, the treatment is given by an export-destination rank in goods trade -- China becoming number one in that rank. In Brazil, public and official language tracks that rank: the 2009 coverage announcing that China had overtaken the United States as the country's largest trading partner was reporting precisely that change.

The primary outcome is absolute UNGA ideal-point distance to China, based on the annual ideal-point estimates of \citet{bailey_etal2017}. Lower values indicate convergence toward China. This measure is preferable to raw annual agreement shares for the main design because it is less sensitive to changes in the UNGA agenda over time. I use resolution-level agreement diagnostics only to interpret where convergence appears strongest. As a measurement-robustness check, the appendix re-estimates the main specifications using ideal points estimated by \citet{fjelstul_etal2026}, which are slightly different from \citet{bailey_etal2017} and based on another sample of resolution-related votes.

For Brazil, the treatment indicator equals one from 2009 onward, the first year China became Brazil's largest export destination. SDiD estimates Brazil's average post-2009 gap relative to a weighted synthetic counterfactual. Unit weights are learned from pre-treatment outcome histories, whereas the optimized pre-treatment time weights use control outcomes before onset and the controls' average outcome after onset \citep{arkhangelsky_etal2021}. The design is reduced-form. Its credibility rests on pre-treatment fit, rank-versus-volume timing tests, donor-pool sensitivity, and outcome robustness.

The SDiD panel combines UNGA ideal points with trade, macroeconomic, power, geographic, institutional, and trade-agreement variables. The complete panel covers 96 countries and 19 Brazil years for the main SDiD window (1997-2015). The preferred estimator uses no covariates: the counterfactual is built from pre-treatment outcomes together with the SDiD unit and time weights. Time-varying variables enter only comparison specifications. Trade data come from the International Trade and Production Database for Estimation \citep{borchert_etal2021}. The ITPD-E \texttt{trade} variable is measured in millions of current US dollars, and export-destination ranks are computed from exporter-importer flows.

The Brazil variables enter the design in three groups. The outcome is Brazil's annual absolute UNGA ideal-point distance to China; the treatment is an indicator for years after China becomes Brazil's largest export destination; and observed country characteristics are used for diagnostics and comparison specifications. The preferred counterfactual is driven by pre-treatment outcomes and SDiD unit and time weights, not by effective covariate adjustment. Contemporaneous trade, macroeconomic, power, ideology, and institutional measures remain available for comparisons but are not preferred because their post-2009 values may be mediators or outcomes of the same shocks.

The panel regression uses the same outcome but constructs treatment separately from goods-only export-destination ranks and a status-current risk set. Table \ref{tab:table-summary-main} summarizes the full country-year panel from which the Brazil specifications are constructed.

\begin{table}[H]
\centering
\caption{\label{tab:table-summary-main}Descriptive statistics for the country-year panel used in the Brazil SDiD design.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8}{10}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lccccc}
\toprule
Variable & N & Mean & SD & Min & Max\\
\midrule
Treatment & 1824 & 0.00 & 0.06 & 0.00 & 1.00\\
UNGA distance to China & 1824 & 0.91 & 0.80 & 0.00 & 4.22\\
UNGA distance to US & 1824 & 2.65 & 0.92 & 0.00 & 5.06\\
Geographic distance to US & 1824 & 0.00 & 0.50 & -1.14 & 1.11\\
Trade share with China & 1824 & -0.01 & 0.49 & -0.36 & 4.96\\
\addlinespace
Trade share with US & 1824 & 0.00 & 0.50 & -0.41 & 1.87\\
Power index & 1824 & 0.00 & 0.50 & -0.12 & 5.01\\
Power gap to US & 1824 & 0.03 & 0.49 & -3.90 & 0.43\\
GDP per capita & 1824 & -0.00 & 0.50 & -0.37 & 2.81\\
Exchange rate & 1824 & -0.00 & 0.49 & -0.15 & 6.82\\
\addlinespace
HoG left ideology & 1824 & 0.40 & 0.49 & 0.00 & 1.00\\
Current account & 1824 & 0.00 & 0.50 & -3.24 & 2.56\\
Government deficit & 1824 & 0.01 & 0.50 & -6.59 & 3.33\\
Parliamentary system & 1824 & 0.39 & 0.49 & 0.00 & 1.00\\
Military executive & 1824 & 0.11 & 0.31 & 0.00 & 1.00\\
\addlinespace
US trade agreement & 1824 & 0.09 & 0.28 & 0.00 & 1.00\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Country-year variables from the SDiD analytic panel; continuous covariates are rescaled in the estimation data, UNGA distances are ideal-point distances, and treatment is binary. Window: 1997-2015 SDiD analytic panel. Observations include Brazil and donor countries used to construct the synthetic counterfactual. The treatment mean is small because only Brazil is treated after 2009. Covariate summaries describe the full analytic panel; the preferred estimate uses none of them.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\subsection{Identification Strategy}\label{identification-strategy}

I want to estimate the causal effect of China rising to first place among a country's export destinations on its foreign policy. The main direct challenge to causal identification is differentiating it from a continuous foreign-policy approximation as exposure to trade with China increases over time. Besides that, countries may move closer to China due to changes in domestic political coalitions or foreign-policy doctrine reorientation that coincide in timing with the treatment, because governments already inclined toward China deepen commercial ties before the rank reversal occurs, or due to any other confounding variable.

To address these issues, I use Synthetic Difference-in-Differences (SDiD). Like the Synthetic Control Method (SCM), it constructs a weighted counterfactual from a donor pool to estimate the causal effect, using weights to approximate the counterfactual in ways that DiD cannot. Unlike the SCM and similar to the DiD, it estimates unit fixed effects, but with different weights. This combines both methods into a single one. As a result, violations of (unweighted average) parallel trends do not mean violations of weighted parallel trends. It also weights pre-treatment periods so that the controls' weighted pre-treatment outcomes approximate their average post-treatment outcomes. In other words, the weights pool observations to reduce bias in a latent factor model, even when global parallel trends are not valid. \citet{arkhangelsky_etal2021} show SDiD is consistent under this latent factor model when weights converge adequately.

The preferred specification uses no covariates because time-varying post-2009 values may induce post-treatment bias. The current-covariate comparison passes the country-year variables listed in Table \ref{tab:outcome-robustness-table} to \texttt{synthdid}; its continuous inputs are rescaled separately, while indicator variables retain their coding. Geographic distance to the United States is time-invariant: it remains in the comparison array but is absorbed by the unit-effect parametrization and supplies no separate adjustment. The producer constructs the power gap as the absolute annual difference between U.S. and country Global Power Index values. On the stored panel support, every country value is weakly below the U.S. value, so the absolute gap equals the signed difference exactly. Separate affine rescaling of country power and the gap does not break their linear dependence once annual components are absorbed. In the covariate-adjusted fit, \texttt{synthdid} treats the covariate coefficients as nuisance parameters and applies the SDiD comparison to the residualized outcome; a nonzero stored coefficient on the gap is not evidence of separate identification. This model is retained only as a sensitivity comparison, and the preferred specification remains covariate-free. Commodity composition and price interactions are separate robustness or mechanism diagnostics, especially because the 2008--2009 interaction includes the first treated year.

I report three distinct inferential summaries for the preferred Brazil estimate. First, the placebo-based standard error is the finite-population standard deviation of 20,000 seeded \texttt{synthdid} placebo resamples. Second, I combine that placebo standard error with a two-sided normal approximation to report the conventional p-value and 95 percent confidence interval. Third, I report deterministic placebo-in-space ranks obtained by reassigning treatment once to Brazil and to every donor: the directional rank counts estimates at least as negative as Brazil's, while the bilateral rank compares absolute magnitudes. The directional rank follows the theory's prediction of convergence; the bilateral rank is a conservative sensitivity assessment.

Two features of rank-based inference with a single treated unit are noteworthy. First, with only 96 countries, the most extreme possible result would be Brazil having the largest effect, yielding a p-value floor of approximately 0.010. Second, the two-sided absolute rank counts large placebo effects of either sign against Brazil, including positive placebo effects that do not represent the error relevant to a directional hypothesis. I apply the same convention throughout the paper to every placebo-based diagnostic.

\subsection{Cross-Country Regression}\label{cross-country-regression}

Notwithstanding my best effort to address potential rival explanations for the observed reduced-form causal effect of the change in 2009, there is only so much one can do with a single treated case. Thus, I also consider a broader panel of countries in which China became the number-one export destination, estimated with a latent interactive fixed-effects regression \citep{liu2024practical}. Interactive fixed effects allow countries to load differently on common latent shocks. Treated countries enter China-top status in different years, so a Brazil-specific 2009 shock cannot mechanically generate the pooled result.

This approach, however, faces some challenges that must be addressed or at least recognized. The conceptual treatment, as mentioned, is status, not the rank. However, for each country what matters is not necessarily being the top trade destination in goods exports. Elsewhere the status cue may track aggregate flows, services exports, or even imports. It all depends on what each country considers more important. It is understandable that a service-oriented country like Malta will weight service trade more than a country like Brazil, where goods exports are what matters.

To better understand variation in the media coverage on this, a supplemental source audit in the appendix uses displaced-incumbent coverage to check evidence of coverage in other countries. Australia illustrates a metric distinction. The \emph{Australian Financial Review} reported on 9 November 2009 that China was Australia's largest aggregate trading partner, combining exports and imports of goods and services. The current goods-only annual panel codes Australia's first qualifying China-top goods-export year as 2009, after Japan held the top goods-export rank in 2008. The AFR item therefore documents broad-metric salience during the same annual treatment window; it does not establish that a strict goods-export cue preceded the 2009 treatment. This mismatch introduces measurement error into the cross-country treatment indicator. If this error is random and nondifferential with respect to potential voting outcomes and their trends, I would expect attenuation toward zero and would therefore interpret the estimated magnitude as conservative under that assumption.

For the cross-country evidence beyond Brazil, the treated sample is restricted to what I call ``durable periods'' of China-top status. A durable period is one in which China is the largest goods-export destination for at least five consecutive observed years, after an observed prior year in which China was not number one.

Since I am interested in a rising power becoming number one, specifically China, I restrict the treatment to years in or after 2000, when it is more plausible that China was seen as a rising power and the status cue would trigger a foreign policy change.

Countries that never reach China-top goods-export status remain controls. I do allow for a country to switch into and out of treatment. Such cases remain in the sample. For treated countries, the main risk set keeps clean pre-entry non-China-top years and qualifying treated years, while excluding post-exit off-status years and short China-top episodes. This operationalization matches the salience logic more closely than either a one-year entry definition or an absorbing treatment rule: the theory expects political visibility, bureaucratic learning, and diplomatic adaptation to be clearer when the new trade hierarchy persists and is currently true. I compute partner ranks from ITPD-E goods sectors only, excluding services before ranks are constructed. I estimate this panel with the \texttt{fect} implementation and refer to it as the IFE specification below. The appendix reports duration-threshold and risk-set robustness checks.

\section{Brazil SDiD Evidence}\label{brazil-sdid-evidence}

The Brazilian analysis estimates the average post-2009 reduced-form effect of China's entry into the top export-destination position on Brazil's UNGA ideal-point distance to China. It asks whether Brazil moved closer to China than a synthetic counterfactual after the 2009 rank reversal.

Figure \ref{fig:brazil-rank-volume} shows the timing of the rank threshold. China's export share rose before 2009, but China became the top-ranked export destination only in 2009. The signed margin over the relevant competitor also changes sign at that threshold.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:brazil-rank-volume}Brazil rank-versus-volume diagnostic for China's export-destination status. Panels show China's export share, ordinal rank, and signed margin over the relevant competitor. The dashed line marks the 2009 rank reversal. Note: Export share in percent; ordinal rank; export-value margin in current USD billions. Window: 2000-2012 annual Brazil series.}]{/Users/manoelgaldino/Documents/DCP/Papers/RDD Trade/red_trade/output/submission/cpsr/raw/cpsr_full_inline_anonymous_files/figure-latex/brazil-rank-volume-1.pdf}}
\caption{\label{fig:brazil-rank-volume}Brazil rank-versus-volume diagnostic for China's export-destination status. Panels show China's export share, ordinal rank, and signed margin over the relevant competitor. The dashed line marks the 2009 rank reversal. Note: Export share in percent; ordinal rank; export-value margin in current USD billions. Window: 2000-2012 annual Brazil series.}
\end{figure}

Figure \ref{fig:plot-sdid} presents the preferred SDiD fit, estimated without covariates. The estimated reduced-form effect of when China became Brazil's largest export destination is negative: the ATT is -0.273 ideal-point units. Substantively, this is a reduction equivalent to 1.35 standard deviations of Brazil's annual pre-treatment distance to China.

The placebo-based SE is 0.131, and the conventional two-sided normal-approximation p-value is 0.037 with a 95 percent interval {[}-0.529, -0.017{]}. Because the theory predicts convergence, the directionally aligned placebo-in-space rank is 3/96 (p = 0.031); the conservative two-sided absolute rank is 7/96 (p = 0.073). I report both rather than treating either convention as the sole inferential benchmark. Interpreting these finite-sample ranks as p-values requires placebo assignments to be sufficiently comparable to Brazil; the appendix therefore discloses donor exposure and pre-fit sensitivity. Relative to Brazil's pre-treatment mean distance (0.647), the ATT corresponds to a 42.2 percent reduction. Appendix Figure \ref{fig:appendix-brazil-china-ideal-points} shows that China's period average changes little around 2009 despite year-to-year volatility, while Brazil shows a more sustained movement toward China.

\begin{figure}[H]
\includegraphics[width=0.95\linewidth]{quality_reports/china_demand_shock_rank_threshold/figure_brazil_sdid_predetermined_core_fit} \caption{Preferred SDiD fit for Brazil and its synthetic comparison, estimated without covariates. Lower values indicate convergence toward China; the arrow shows the level-adjusted SDiD ATT, equal to the average post-2009 contrast net of the SDiD-weighted pre-treatment contrast; it is not the raw vertical distance between the trajectories. Note: Absolute UNGA ideal-point distance to China. SE: placebo-based SE with 20,000 replications; p-values reported in the text and table. Window: 1997-2015 annual Brazil series.}\label{fig:plot-sdid}
\end{figure}

Figure \ref{fig:plot-placebo-distribution} shows the placebo-in-space distribution behind that inference. Brazil sits in the left tail of the estimates obtained by reassigning treatment to each donor in turn.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:plot-placebo-distribution}Distribution of placebo-in-space estimates across the 95 donor assignments, with Brazil marked. Brazil's estimate is the 3rd most negative of 96 assignments (directional p = 0.031); the two-sided absolute rank is 7/96 (p = 0.073). Negative values indicate convergence toward China. Note: Estimated post-2009 gap in absolute UNGA ideal-point distance to China. Window: 1997-2015 annual SDiD panel.}]{/Users/manoelgaldino/Documents/DCP/Papers/RDD Trade/red_trade/output/submission/cpsr/raw/cpsr_full_inline_anonymous_files/figure-latex/plot-placebo-distribution-1.pdf}}
\caption{\label{fig:plot-placebo-distribution}Distribution of placebo-in-space estimates across the 95 donor assignments, with Brazil marked. Brazil's estimate is the 3rd most negative of 96 assignments (directional p = 0.031); the two-sided absolute rank is 7/96 (p = 0.073). Negative values indicate convergence toward China. Note: Estimated post-2009 gap in absolute UNGA ideal-point distance to China. Window: 1997-2015 annual SDiD panel.}
\end{figure}

Table \ref{tab:brazil-sdid-diagnostic-summary} summarizes the diagnostic package behind the preferred Brazil SDiD estimate. The top five donors are Georgia 3.1\%, Singapore 2.9\%, Chad 2.8\%, Guatemala 2.7\%, Paraguay 2.7\%, and the complete donor pool, along with pre-treatment time weights and sensitivity diagnostics based on donor-deletion and window tests, appears in Appendix Tables \ref{tab:sdid-unit-weights-complete}, \ref{tab:sdid-time-weights}, \ref{tab:sdid-donor-sensitivity}, and \ref{tab:sdid-window-sensitivity}.

\clearpage

\begingroup\singlespacing
\renewcommand{\arraystretch}{1.02}
\begin{table}[!h]
\centering
\caption{\label{tab:brazil-sdid-diagnostic-summary}Brazil SDiD diagnostics: fit, placebo inference, and sensitivity. Preferred estimate: -0.273 ideal-point units (1997--2015; treatment begins in 2009).}
\centering
\fontsize{10}{12}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{10.6cm}>{\raggedleft\arraybackslash}p{3.7cm}}
\toprule
\textbf{Measure} & \textbf{Result}\\
\midrule
\addlinespace[0.7em]
\multicolumn{2}{l}{\textbf{A. Donor weights: concentration of the comparison group}}\\
\hspace{1em}Number of donors & 95\\
\hspace{1em}Largest donor weight & 3.1\%\\
\hspace{1em}Combined weight of the five largest donors & 14.4\%\\
\addlinespace[0.7em]
\multicolumn{2}{l}{\textbf{B. Pre-treatment fit: prediction error after adjusting levels}}\\
\hspace{1em}Pre-treatment prediction error (RMSPE) & 0.058\\
\hspace{1em}Post-treatment / pre-treatment RMSPE & 5.54\\
\hspace{1em}Brazil's pre-treatment mean distance to China & 0.647\\
\addlinespace[0.7em]
\multicolumn{2}{l}{\textbf{C. Placebo inference: Brazil's rank among all assignments}}\\
\hspace{1em}Directional rank (convergence toward China) & 3/96 (p = 0.031)\\
\hspace{1em}Two-sided rank (absolute effect size) & 7/96 (p = 0.073)\\
\addlinespace[0.7em]
\multicolumn{2}{l}{\textbf{D. Donor sensitivity: exclusions and exposure to China}}\\
\hspace{1em}Largest change when dropping one of the top ten donors & 3.6\%\\
\hspace{1em}Estimate after dropping all ten highest-weight donors & -0.268\\
\hspace{1em}Weight on high-weight donors with China in their top two & 10.2\%\\
\addlinespace[0.7em]
\multicolumn{2}{l}{\textbf{E. Windows and timing: point-estimate diagnostics}}\\
\hspace{1em}Windows with a negative estimate (including preferred) & 7 of 7\\
\hspace{1em}Range of estimates across windows & -0.320 to -0.256\\
\hspace{1em}2004 onset: China rank 2 (post-period: 2004--2008) & -0.109\\
\hspace{1em}2009 onset: China rank 1 (post-period: 2009--2015) & -0.273\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item SDiD = Synthetic Difference-in-Differences; preferred specification has no covariates. Estimates and root mean squared prediction error (RMSPE) are in absolute UNGA ideal-point distance to China; negative estimates indicate convergence. RMSPE removes the mean pre-treatment gap. Placebo ranks include Brazil and 95 donor assignments; their p-value interpretation requires comparable assignments. In D, changes are relative to the preferred estimate; high-weight donors are the top ten, and exposure means China is a top-two export destination in at least one year during 2009--2015 (share of total donor weight). D--E report point estimates, without recomputed inference. Full donor and time weights and all sensitivity results appear in the appendix. The 2004 and 2009 onset rows use different pre- and post-onset periods and separately fitted counterfactuals; their ordering is suggestive and does not establish a statistically significant difference between effects.
\end{tablenotes}
\end{threeparttable}
\end{table}

\endgroup

Table \ref{tab:outcome-robustness-table} reports the preferred Brazil SDiD estimate alongside four comparisons. Column (1) uses no covariates and is preferred because it avoids conditioning the counterfactual on variables observed after 2009. Column (2) restores the full contemporaneous covariate matrix; column (3) removes institutional variables but retains the other contemporaneous measures; column (4) changes the donor pool to Latin America using the contemporaneous matrix; and column (5) applies the preferred no-covariate specification to that regional pool, which makes it the column comparable with (1). All five estimates are negative, but columns (2)--(4) are sensitivity checks rather than alternative candidates for the main specification.

One may wonder whether a synthetic control built from donors all over the world is a good counterfactual for Brazil. Column (5) re-estimates the preferred specification on a donor pool restricted to Latin American countries. The estimated effect is larger in absolute terms, -0.326 against -0.273 in the global pool, and Brazil is the 2nd most negative of 20 assignments in the directional placebo comparison (p = 0.100). The regional pool is small, which limits what either inference convention can show: with 20 units the rank test cannot fall below 0.050 however extreme Brazil is, and the placebo standard error rises from 0.131 to 0.207, so the normal-approximation interval includes zero. Figure \ref{fig:plot-latam} reports the regional fit.

\begin{table}[H]
\centering
\caption{\label{tab:outcome-robustness-table}Brazil SDiD estimates across main and robustness specifications.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lccccc}
\toprule
  & (1) Preferred: no covariates & (2) Current covariates & (3) No institutions & (4) Latin America, covariates & (5) Latin America, none\\
\midrule
ATT & -0.273** & -0.268* & -0.269* & -0.408** & -0.326\\
 & (0.131) & (0.143) & (0.143) & (0.207) & (0.207)\\
\textit{Covariates:} &  &  &  &  & \\
Trade share China &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
Trade share US &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
\addlinespace
Power index (GPI) &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
Power gap to US &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
Per-capita income &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
Exchange rate &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
Geographic distance to US &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
\addlinespace
HoG left ideology &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
Current account (\% GDP) &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
Gov. deficit (\% GDP) &  & $\checkmark$ & $\checkmark$ & $\checkmark$ & \\
Parliamentary system &  & $\checkmark$ &  & $\checkmark$ & \\
Military executive &  & $\checkmark$ &  & $\checkmark$ & \\
\addlinespace
US trade agreement &  & $\checkmark$ &  & $\checkmark$ & \\
Country-years & 1,824 & 1,824 & 1,824 & 380 & 380\\
Donor countries & 95 & 95 & 95 & 19 & 19\\
Donor pool & Global & Global & Global & Latin America & Latin America\\
Time window & 1997-2015 & 1997-2015 & 1997-2015 & 1997-2015 & 1997-2015\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item The outcome is absolute UNGA ideal-point distance to China; ATT is the estimated average causal effect on Brazil after 2009, so negative values mean convergence. ATTs are reported with three decimals. Placebo-based SEs are in parentheses (20,000 replications for columns (1) and (5), which use the preferred no-covariate specification; 5,000 for comparison columns (2)-(4)). Stars use two-sided normal-approximation p-values based on placebo SEs: * p < 0.10; ** p < 0.05; *** p < 0.01. Checkmarks show included covariate groups. Donor counts exclude Brazil. Column (1) uses no covariates, so its covariate cells are left blank. Columns (2)-(4) use contemporaneous covariates and are comparisons. Column (5) applies the preferred no-covariate specification to the Latin American donor pool, so it is the column comparable with (1); its directional placebo rank is 2/20 (p = 0.100), against a floor of 0.050 imposed by the size of the regional pool. For column (1), the directional rank is 3/96 (p = 0.031) and the bilateral absolute rank is 7/96 (p = 0.073).
\end{tablenotes}
\end{threeparttable}}
\end{table}

The rank interpretation requires more than showing that trade with China was increasing. Brazil's exports to China grew before 2009, including years in which China rose in the export hierarchy but did not become number one. Table \ref{tab:table-placebo} therefore reports outcome-path timing falsifications without covariates: using no covariates prevents variables measured after the early pseudo-onsets from entering those comparisons. The 2003, 2004, and 2005 estimates are smaller in absolute value than the 2009 rank-one estimate; 2004 is especially useful because China first reaches rank 2 but is still not Brazil's largest export destination. The 2012 row probes a later break after China had already become the top destination. Each row refits the SDiD counterfactual over a different pre- or post-onset window. The early estimates average 2003--2008, 2004--2008, and 2005--2008, compared with 2009--2015 for the preferred estimate and 2012--2016 for the later break. Their ordering is suggestive timing evidence, not a comparison of a common estimand or a test that the effects differ. No uncertainty for differences between rows is reported, and the 2012 fit uses already-treated years in its nominal pre-period.

The same timing logic addresses the main Brazilian political confounder. President Lula da Silva took office in 2003 and pursued a more explicit South-South foreign-policy agenda, a shift emphasized in work on Brazilian autonomy, presidential foreign policy, and international engagement \citep{neto2011, mouron_urdinez2014, neto_malamud2015, rodrigues2019measuring, schenoniMythsMultipolaritySources2022}. The 2003 and 2005 pseudo-onsets yield smaller point estimates in absolute value, providing suggestive evidence against an immediate large break. Because these estimates cover different periods and refit the counterfactual, they do not establish that the early and 2009 effects differ or exclude a gradual or delayed Lula-era shift. The cross-country panel also estimates the rank-threshold pattern across countries with different political systems and leadership profiles, which reduces the concern that the Brazil estimate is only a Lula-period artifact.

The main rival explanation for the proposed effect of a discrete status change is that Brazil's estimated convergence simply reflects a continuous increase in its export dependence on China. Under this account, UNGA alignment should respond smoothly to the degree of trade exposure to China. The pattern shown in Figure \ref{fig:brazil-rank-volume} is compatible with this possibility: Brazil's export exposure increased well before 2009, raising the concern that nothing distinctive occurred at the rank-one threshold and that the estimated effect instead reflects Brazil's growing commercial ties with China.

To assess this possibility, I relate each donor country's placebo-in-space pseudo-ATT to the change in its export share directed to China. By construction, the donor pool excludes countries in which China became the largest goods-export destination during the 1997--2015 estimation window. These countries therefore provide variation in trade exposure below the rank-one threshold. If continuous exposure drives alignment, donors experiencing larger increases in exposure should exhibit more negative pseudo-ATTs -- that is, greater convergence toward China. A flat or positive relationship would instead weaken this rival explanation, although it would not by itself establish that status is the operative mechanism.

Figure \ref{fig:rival-hypothesis} provides little support for the continuous-exposure account. Panel A measures exposure using goods trade, matching the sectoral definition used to assign treatment, while Panel B uses all-sector trade, including both goods and services. The relationship is essentially flat under both measures. The OLS slopes are 0.0002 and 0.0007 per percentage point, respectively, while the corresponding Spearman correlations are 0.034 and 0.037. Under either measure, Brazil's ATT is also more negative than those of 23 of the 24 donors in the highest quartile of exposure growth. These patterns do not rule out a role for continuous export dependence, nor do they identify a discontinuity at the rank threshold itself, but they make it less plausible that Brazil's result is driven simply by rising trade exposure to China.

\begin{figure}[!htbp]
\includegraphics[width=1\linewidth]{images/figure_brazil_sdid_dose_response_panel} \caption{Trade-exposure dose and placebo-in-space pseudo-ATTs among 95 donor countries. Each donor is assigned the same 2009 pseudo-treatment, and dose is the difference between its mean annual export share directed to China in 2009--2015 and 1997--2008. Panel A measures goods trade; Panel B measures all-sector trade, including goods and services. Negative pseudo-ATTs indicate convergence toward China. Dark points identify donors in the top quartile of dose, vertical dotted lines mark the corresponding cutoffs, and black lines are descriptive OLS fits. The orange dashed horizontal line marks Brazil's ATT of -0.273; Brazil has no dose coordinate and therefore does not enter either fit. No donor had China as its largest goods-export destination during 1997--2015, so the figure shows only the dose gradient below the rank-one threshold and does not identify a discontinuity at that threshold. Donor pseudo-ATTs are estimated from overlapping pools, so no standard error is reported for either slope.}\label{fig:rival-hypothesis}
\end{figure}

A remaining concern is that 2009 bundled the Brazilian rank reversal with other contemporaneous shocks, including the global financial crisis, the BRICS/G20 moment, and the commodity cycle. Table \ref{tab:china-demand-sdid-diagnostics} uses measures built from external goods exports only to address this critique. The exposure baselines are country means over 2004--2008: primary goods as a share of external goods exports, its Agriculture and Mining and Energy components, and China as a share of external goods exports. In the table, \texttt{x\ 2008-\/-2009} means that the fixed 2004--2008 exposure is multiplied by an indicator for 2008 and 2009 and then standardized over the stored 1997--2016 input panel before restriction to the 1997--2015 estimation window. The price diagnostic instead weights World Bank Pink Sheet log-price changes relative to 2007 by the country's 2004--2008 Agriculture, Energy, and Metals and Minerals export shares, activates that index in 2008--2009, and standardizes it over the same stored 1997--2016 input panel before the 1997--2015 estimation-window restriction. Only these time-varying interactions enter the four diagnostic specifications: exposure levels are time-invariant and absorbed by unit effects, while the common 2008--2009 indicator is absorbed by time effects.

Brazil's 2004--2008 primary-goods share is 29.04 percent, composed of 11.25 percent Agriculture and 17.79 percent Mining and Energy. The preferred ATT is -0.273; adding primary composition and its 2008--2009 interaction yields -0.285. Composition, decomposition, global-price, and prior-China-exposure specifications remain in a narrow negative range. The 2008--2009 interactions are robustness or mechanism diagnostics, not alternative total-effect estimates, because 2009 is the first treated year and the interaction may absorb part of the mechanism. Stability across these measures does not isolate the rank cue experimentally from every 2009 political shock, but it reduces the narrower concern that the preferred estimate is an artifact of post-treatment controls or omitted pre-2009 commodity composition.

The cross-country panel below is a broader scope check, not the main answer to the Brazil-specific demand-shock critique. Brazil is included in the goods-only cross-country sample, but the panel aligns countries by their own China-top goods-export entry years. A Brazil-specific 2009 confounder cannot mechanically generate an average event-time effect across countries treated in different calendar years. For such an explanation to account for both the Brazil estimate and the cross-country result, the omitted force would need to coincide with durable China-top entry across countries, affect UNGA distance to China in the same direction, and remain outside the latent factors captured by the interactive fixed-effects specification. It would also need to be strongly enough associated with both treatment timing and the outcome to overturn estimates that are stable across the donor-pool checks and the cross-country duration and risk-set checks, alongside the suggestive Brazil timing diagnostics.

\begin{table}[H]
\centering
\caption{\label{tab:table-placebo}Brazil SDiD rank-versus-volume timing diagnostics without covariates.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8}{10}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{clccccl}
\toprule
Timing year & Test role & China rank & Export share (\%) & Margin (USD bn) & ATT & Inference\\
\midrule
2003 & Growth/lower-rank promotion & 3 & 6.7 & -12.9 & -0.064 & Point estimate only; no covariates\\
2004 & China rank-2 threshold & 2 & 7.4 & -14.2 & -0.109 & Point estimate only; no covariates\\
2005 & Rapid growth without rank 1 & 3 & 7.2 & -16.7 & -0.099 & Point estimate only; no covariates\\
2009 & Actual rank-1 reversal & 1 & 15.1 & 4.1 & -0.273 & Point estimate only; no covariates\\
2012 & Later-break falsification & 1 & 18.8 & 14.9 & -0.100 & Point estimate only; no covariates\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Outcome is absolute UNGA ideal-point distance to China; ATT denotes the SDiD estimate for Brazil after each nominal onset; negative values indicate convergence; export margins are current USD billions. Window: all windows begin in 1997. Post-onset periods are 2003-2008, 2004-2008, 2005-2008, 2009-2015, and 2012-2016 (6, 5, 4, 7, and 5 years). All rows use Brazil and the same 95 donors, without covariates, but refit unit and time weights for each window and onset. These are suggestive diagnostics with different estimands, not tests of differences between effects; no uncertainty for the cross-row contrasts is reported. The 2012 nominal pre-period includes already-treated years. The preferred 2009 estimate and its inference are reported separately in the main specification.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\begin{table}[H]
\centering
\caption{\label{tab:china-demand-sdid-diagnostics}Brazil SDiD estimates under corrected predetermined commodity and China-demand diagnostics.}
\centering
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lcccc}
\toprule
Specification & ATT & Placebo SE & Normal p & Rank p (dir./bilat.)\\
\midrule
Current covariates & -0.268 & 0.143 & 0.061 & Not computed\\
Preferred: no covariates & -0.273 & 0.131 & 0.037 & 0.031 / 0.073\\
Primary share x 2008-2009 & -0.285 & 0.129 & 0.027 & 0.031 / 0.073\\
Agriculture/mining x 2008-2009 & -0.284 & 0.128 & 0.026 & Not computed\\
Price exposure x 2008-2009 & -0.277 & 0.130 & 0.034 & Not computed\\
\addlinespace
Prior China share x 2008-2009 & -0.284 & 0.130 & 0.029 & Not computed\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Outcome is absolute UNGA ideal-point distance to China; ATT is the estimated average causal effect on Brazil after 2009, so negative values mean convergence. SE: synthdid placebo SE with 20,000 replications for the preferred row and 5,000 with a common seed for comparison rows. Window: 1997-2015 annual SDiD panel. All rows keep the binary 2009 onset. The preferred row uses no covariates; other rows are diagnostics, and the 2008--2009 interactions include the first treated year. Rank inference was computed only for the preferred and primary-share interaction rows; 'Not computed' does not denote a failed test.
\end{tablenotes}
\end{threeparttable}
\end{table}

\subsection{Issue-Area Evidence: Where Did Convergence Occur?}\label{issue-area-evidence-where-did-convergence-occur}

The aggregate ideal-point estimate raises a substantive question: in what kinds of votes did Brazil move closer to China? Resolution-level diagnostics suggest that the post-2009 convergence was selective rather than uniform. Figure \ref{fig:plot-brazil-china-unvotes-issue-year} disaggregates the convergence rate by year and substantive issue family. In several issue areas Brazil and China already voted together at high rates before treatment, leaving little room for additional convergence. The more informative domain is human rights, where pre-treatment agreement was lower and where movement toward China carried greater reputational costs for Brazil, given the domestic and international implications of Brazil's human-rights foreign policy \citep{milani2015humanrights}.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:plot-brazil-china-unvotes-issue-year}Brazil-China identical UNGA votes by issue area, 2005-2012. Points report annual shares; the vertical line marks 2009. The clearest pattern expected by the mechanism is selective convergence in human rights. Note: Percentage of roll-call resolutions with identical Brazil-China votes. Window: 2005-2012 annual series; multi-coded resolutions enter each issue family.}]{/Users/manoelgaldino/Documents/DCP/Papers/RDD Trade/red_trade/output/submission/cpsr/raw/cpsr_full_inline_anonymous_files/figure-latex/plot-brazil-china-unvotes-issue-year-1.pdf}}
\caption{\label{fig:plot-brazil-china-unvotes-issue-year}Brazil-China identical UNGA votes by issue area, 2005-2012. Points report annual shares; the vertical line marks 2009. The clearest pattern expected by the mechanism is selective convergence in human rights. Note: Percentage of roll-call resolutions with identical Brazil-China votes. Window: 2005-2012 annual series; multi-coded resolutions enter each issue family.}
\end{figure}

In that domain, Brazil-China identical voting increased by 7.5 percentage points after 2009. This pattern is consistent with the proposed mechanism because it locates the clearest movement in a visible multilateral arena where Brazil had previously maintained more distance. It does not, however, show that the trade-rank cue itself caused the selective shift or that policymakers relied on it in particular decisions.

The strongest support comes from human-rights resolutions in which China and the United States diverged, where Brazil moves closer to China relative to comparable donor countries after 2009.

This descriptive increase does not by itself establish China-specific alignment, because annual issue-area shares can reflect agenda composition and do not compare Brazil with donor countries. To address such issues, I ran regressions with country and resolution fixed effects, restricted to human-rights votes where China and the United States cast different votes.

The results show that Brazil moves closer to China after 2009 relative to the donor pool. The Brazil-by-post-2009 coefficient is -0.357 for distance to China minus distance to the United States (model-based SE = 0.021), and -0.414 when the sample is restricted to strong yes/no China-US disagreements (model-based SE = 0.023). The corresponding non-human-rights estimate is smaller (-0.131, model-based SE = 0.012). These are not causal estimates, given the usual selection and omitted-variable concerns.

However, restricting attention to a single issue domain opens a design that ideal points computed over all votes cannot support: a triple difference. Ideal points compress every resolution in a session into one score, leaving no contrast between issue domains to exploit, whereas vote-level data preserve it. Thus, I can not only compare the difference between Brazil and other untreated countries before and after (traditional DiD), but also include a third difference: across domains within the same country and year, comparing Brazil with the donor pool, before and after 2009, in human-rights votes relative to every other vote. Identification here asks for more than parallel trends between treated and control units: whatever bias a non-parallel trend introduces must be the same in the two issue domains, so that it cancels in the third difference \citep{olden_moen2022}. Appendix Figure \ref{fig:plot-ddd-pretrends} displays the pre- and post-2009 Brazil-donor gaps in both domains; this descriptive comparison does not establish the identifying restriction.

Let \(B_i\) identify Brazil, \(P_r\) indicate 2009--2012, and \(H_r\) identify a human-rights resolution. The vote-level specification is
\[
Y_{ir}=\alpha_i+\lambda_r+\beta(B_iP_r)+\gamma(B_iH_r)+\delta(B_iP_rH_r)+\varepsilon_{ir}.
\]
Country and resolution fixed effects absorb the remaining lower-order terms. The Brazil-by-domain interaction allows Brazil's pre-existing gap relative to donors to differ between human-rights and other resolutions. The coefficient \(\delta\) measures the additional post-2009 human-rights shift. The sample contains 55,190 observed votes by 95 countries on 612 China-US divergent resolutions in 2005--2012. Votes are scored \(-1\) for no, \(0\) for abstain, and \(1\) for yes. The outcome is \(Y_{ir}=|s_{ir}-s_{Cr}|-|s_{ir}-s_{Ur}|\), where \(s_{Cr}\) and \(s_{Ur}\) are China's and the United States' scores; negative values indicate a vote closer to China. Country-resolution pairs without a recorded yes, no, or abstain vote -- whether because of absence, nonparticipation, or another reason -- do not enter the observed-vote sample. A resolution enters the China-U.S. divergent sample only when both China and the United States have recorded votes and their scores differ. Any human-rights tag places a resolution in the human-rights group; all remaining resolutions form the non-human-rights group. Each observed country-resolution vote receives equal weight. The specification does not absorb a separate domain intercept for each donor country; interpretation also requires changes in donor vote availability not to generate the differential shift across domains.

The DDD estimate is -0.222 for distance to China minus distance to the United States (country-clustered model-based SE = 0.014). Its negative sign indicates a larger shift toward China in human-rights votes. With Brazil as the single treated country, I also reassign the treated-country role to each country, rebuilding all three interactions and retaining the same sample and fixed effects. In this DDD-specific distribution, Brazil ranks 9 of 95 in the predicted direction (inclusive directional tail share = 0.095; strict donor-only share = 0.085; two-sided absolute share = 0.126). These are descriptive reassignment benchmarks; interpreting them as randomization inference requires exchangeability of country assignment.

The separate human-rights-only DiD estimate of -0.357 ranks 6 of 95 in its own country-placebo distribution (inclusive directional share = 0.063; strict donor-only share = 0.053). This benchmark evaluates the within-domain post-2009 contrast, whereas the DDD benchmark evaluates the additional shift across domains.

\begin{table}[H]
\centering
\caption{\label{tab:issue-area-prepost-table}Brazil-China identical UNGA votes by issue area, before and after 2009.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8}{10}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lrrrl}
\toprule
Issue area & Pre-2009 identical vote share & Post-2009 identical vote share & Change & Interpretation\\
\midrule
Human rights & 69.6 & 77.1 & 7.5 & Politically costly convergence; mechanism-informative\\
Arms/disarmament/nuclear & 83.0 & 84.3 & 1.2 & Diagnostic evidence\\
Economic development & 92.9 & 90.0 & -2.9 & Diagnostic evidence\\
Decolonization & 94.1 & 98.1 & 4.0 & Diagnostic evidence\\
Palestine/Middle East & 100.0 & 100.0 & 0.0 & High baseline agreement; limited room to move\\
\addlinespace
Other / uncoded & 73.4 & 83.1 & 9.7 & Heterogeneous residual category\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Percentage of roll-call resolutions with identical Brazil-China votes. Window: 2005-2008 versus 2009-2012; multi-coded resolutions enter each issue family. Rows are label-specific diagnostics, not a mutually exclusive decomposition of the aggregate convergence pattern.
\end{tablenotes}
\end{threeparttable}}
\end{table}

The DDD estimate indicates a larger human-rights shift than the analogous non-human-rights shift. Its country-placebo distribution provides moderate evidence for that additional shift and counsels against language implying that Brazil is unique. The Brazil evidence therefore supports a cautious claim of selective UNGA adjustment toward China in politically visible domains, rather than a claim that Table \ref{tab:issue-area-prepost-table} alone proves selective convergence.

\section{Brazilian Media Salience}\label{brazilian-media-salience}

To assess whether trade-topic salience increased around the rank reversal, I examine coverage of China in Folha de S.Paulo, Brazil's widest-circulation newspaper \citep{folha2016}, from 2000 to 2014. Salience matters because the rank-threshold argument requires the top-rank cue to become politically usable. A change in export hierarchy can shape elite and public attention when it appears in a prominent national newspaper as a simple signal of China's commercial importance, consistent with work on media, agenda setting, and foreign policy \citep{soroka2003, baum_potter2008, walgraveContingencyMassMedias2006}.

Headlines are the appropriate unit for this trade-topic diagnostic because they are tractable in large archives and operate as attention-directing cues \citep{zhang_yu2024_chinese_dream}. The relevant question is whether Folha increasingly foregrounded China as a trade relationship after the rank reversal. Headlines are the most visible textual cue in the archive and the part of coverage most likely to be scanned by broad audiences. Full article texts would be useful for a different exercise -- for example, measuring tone or detailed argumentation -- but the salience claim here is about which China-related themes were made visible at the headline level. This diagnostic does not measure the frequency of explicit rank labels.

The preserved retrieval code specifies a Folha site search for \texttt{china}, orders the results from oldest to newest, extracts the displayed title and date, retains one record per exact title, and then keeps titles containing \texttt{China}, \texttt{chinês}, or \texttt{chinesa}. The classified headline file is frozen as an analysis input rather than regenerated during manuscript rendering. The archive does not contain the raw page responses or contemporaneous page-level logs needed to certify the historical search as exhaustive, and the boundary years 2000 and 2014 do not have complete annual coverage.

I therefore classify China-related headlines into substantive categories and then collapse them into four analytically relevant groups: China-Brazil trade, China's domestic economy, diplomacy and bilateral relations, and non-economic coverage. The classification uses a fixed label set with examples, and the appendix reports the exact prompt and validation procedure. Figure \ref{fig:plot-media-counterfactual} compares 2000--2008 with 2009--2014 and shows a substantial increase in China-Brazil trade coverage, from an average of 47 to 73 headlines per year (about 55 percent), alongside a larger increase in coverage of the Chinese economy, from 147 to 311 headlines per year (about 111 percent). Together, these patterns are consistent with increased media attention to China's economic importance for Brazil, as the proposed mechanism predicts. The figure supports the trade-topic-salience step, but it does not by itself establish the public availability of an explicit rank cue. The separate contemporary sources below provide evidence about rank language.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:plot-media-counterfactual}Brazilian media salience: disaggregated China headlines in Folha de S.Paulo by category. From 2000--2008 to 2009--2014, China-Brazil trade coverage increases substantially and coverage of the Chinese economy increases even more; together, the changes are consistent with heightened attention to China's economic importance for Brazil. Note: Headlines per category per year. Window: 2000-2014 annual series.}]{/Users/manoelgaldino/Documents/DCP/Papers/RDD Trade/red_trade/output/submission/cpsr/raw/cpsr_full_inline_anonymous_files/figure-latex/plot-media-counterfactual-1.pdf}}
\caption{\label{fig:plot-media-counterfactual}Brazilian media salience: disaggregated China headlines in Folha de S.Paulo by category. From 2000--2008 to 2009--2014, China-Brazil trade coverage increases substantially and coverage of the Chinese economy increases even more; together, the changes are consistent with heightened attention to China's economic importance for Brazil. Note: Headlines per category per year. Window: 2000-2014 annual series.}
\end{figure}

\clearpage

The evidence distinguishes public availability from official uptake. The status cue became publicly available during the 2009 treatment year, before the full-year trade table was finalized. In early May, contemporary coverage of January--April trade statistics reported a historic shift in Brazil's trade hierarchy: China had become Brazil's largest trading partner and had purchased US\$5.627 billion in Brazilian exports, compared with US\$4.925 billion purchased by the United States \citep{agencia_brasil2009_china_supera}. This real-time visibility matters for the mechanism. The empirical design codes treatment annually because the outcome and comparative trade data are annual, but officials, journalists, and firms encountered the rank cue through contemporaneous monthly and year-to-date statistics. Lula's May 2009 Beijing visit then provides evidence of official uptake during the treatment year: the new rank was already available as a public category around which diplomatic priorities could be narrated. Brazilian officials subsequently invoked China's new position in Brazil's trade hierarchy when explaining diplomatic prioritization, bilateral upgrading, and institutional follow-up.

In a written interview on the eve of his May 2009 visit to Beijing, President Lula described China as Brazil's leading trading partner and framed the trip as an effort to consolidate cooperation across commerce, technology, and global economic governance \citep[323]{mre_funag_resenha104_2009}. In Beijing three days later, Lula repeated the rank claim in speeches organized around the Brazil-China Strategic Partnership, trade diversification, investment, presidential diplomacy, and the preparation of the 2010--2014 Joint Action Plan \citep[115, 121--122]{mre_funag_resenha104_2009}. The cue then persisted in Itamaraty language. When announcing Hu Jintao's 2010 state visit and the signature of the Joint Action Plan, the Ministry of Foreign Affairs again invoked China's 2009 rise to the top of Brazil's trade hierarchy \citep[356]{mre_funag_resenha106_2010}. Dilma Rousseff and Hu Jintao's 2011 joint communiqué likewise noted that China had become Brazil's principal trading partner in 2009 and embedded that status in an agenda of intensified dialogue over trade, investment, diversification, and implementation of the Joint Action Plan \citep[160--161]{mre_funag_resenha108_2011}. Later that year, Foreign Minister Antonio Patriota made the institutional link explicit: in discussing China, he announced a dedicated Itamaraty task force to monitor economic-commercial relations with Brazil's principal trading partner and to propose ways to move the relationship beyond complementarity, toward diversification and higher value-added trade \citep[47]{mre_funag_resenha109_2011}.

These statements show official uptake of the 2009 status cue. Their co-occurrence with diplomatic prioritization and institutional attention is consistent with justificatory use, but it does not demonstrate that the cue caused those initiatives or particular UNGA decisions. The evidence therefore supports the availability and uptake steps directly and treats justificatory use as an inference compatible with the public mechanism implied by the theory: once China was officially recognized as central in Brazil's economic hierarchy, selective diplomatic accommodation could be presented as pragmatic recognition of national economic interests rather than as ideological concession or opportunistic bandwagoning.

\section{Cross-Country Evidence Beyond Brazil}\label{cross-country-evidence-beyond-brazil}

The cross-country analysis serves two purposes. First, it examines whether a first position as a goods export destination is followed by movement toward China beyond the Brazilian case. Second, it is an additional robustness check against explanations tied specifically to Brazil's 2009 calendar year, such as the global financial crisis, the BRICS/G20 moment, or the commodity cycle.

However, operationalizing the analysis with multiple countries poses several difficulties. As the formal model shows, the public cue should increase the probability of a policy shift, all else equal.\footnote{Strictly speaking, the model is deterministic. Here, however, I treat the timing of treatment as stochastic, which allows me to speak of an increase in probability.} Thus, with the assistance of artificial intelligence, I searched press sources for all potentially treated countries in which a public cue could have occurred. I found high-quality data only for Australia, Chile, Uruguay, Gabon, and Qatar. However, since absence of evidence is not evidence of absence, I cannot say that no public cue occurred in the other countries. Thus, because public salience is not measured directly outside Brazil, the panel does not by itself validate the top trade rank position as a proxy for public status change or extend the public cue mechanism to the larger sample.

Another difficulty is that the treatment is the public cue, but the model does not distinguish which trade statistic drives it. For each country, the cue may occur when China becomes the leading destination for merchandise exports alone; in countries where services matter more, it may instead arise from goods and services combined, or even services alone; and in other cases, it may be total trade flows (exports plus imports). Thus, for each country, it is unclear which statistic is relevant for identifying a potential treatment. The Australian case is illustrative. The Australian Financial Review (AFR) headlines said ``China hits the spot as trading partner'', referring to imports plus exports and mentioning in the text that 2009 was the third year it was in that leading position. To complicate matters further, AFR uses the fiscal year 2006-2007, not the calendar year. Should I code the beginning of treatment in 2010 (when China became the top export destination), 2007 (when I found the public cue evidence), or perhaps 2008 (because the fiscal year ended mid-2007)? Finally, if a country is already very close to China before treatment---as is the case of Gabon; see Figure \ref{fig:public-cue-pre-treatment-distance} in the Appendix---there are no gains from shifting its foreign-policy stance.

To address these problems, I estimated a separate SDiD model for each of the countries for which I have data on the public cue and in which there was room for foreign-policy adjustment toward China: Chile, Uruguay, and Australia. I excluded Gabon, which was already very close to China before treatment, and Qatar, whose treatment occurred only in 2021, leaving too little time for the effect to emerge. For Australia, I use 2007 as the theoretically preferred public-cue date and retain 2010, when China became the top goods-export destination, as a robustness timing. The corresponding estimand is the ATT on absolute UNGA ideal-point distance to China.

The case-specific estimates are mixed (see Appendix Table \ref{tab:public-cue-sdid-results}). Chile and Uruguay have negative estimates, in the direction of convergence, but both are imprecise. The Australian estimates for 2007 and 2010 are positive, in the direction of greater distance from China, and are also imprecise. All four 95 percent intervals include zero. For the theoretically preferred 2007 public-cue timing, the ATT is 0.128 ideal-point units (placebo SE = 0.161; two-sided normal-approximation p = 0.424; 95 percent CI: {[}-0.187, 0.444{]}). The p-value and interval use a normal approximation based on the placebo standard error.

Australia is therefore an opposite-direction case rather than evidence of convergence. In fiscal year 2006-07, China became Australia's largest trading partner, the news covered the change, and a public cue occurred. By the end of the year, the Labor government came to power. Yet the point estimate indicates greater distance from China, although the uncertainty is substantial.

When Labor's Kevin Rudd took office as prime minister by the end of 2007, he had made clear before taking office that he was concerned about when the China boom would end \citep{uhlmann2007rudd}. In fact, in his second term in power, in 2013, when the boom was over, he recalled saying so years earlier \citep{rudd2013economy}. As the formal model makes clear, the direction of adjustment depends on the perceived benefits and costs of alignment with China. Increased interdependence can be seen as a risk, and Australia's close ties with the West, particularly the United States and United Kingdom, are long and well known. This contrasts sharply with Brazil, the paper's main case. The opposite-direction Australian estimate is therefore compatible with perceived costs dominating perceived benefits. Because those perceptions are not measured and the estimate is imprecise, however, the result does not by itself validate that mechanism.

To reduce dependence on any one selected case, I also report an interactive fixed-effects framework pooling the cases. Among Australia, Brazil, Chile, and Uruguay, the pooled estimates are negative under both comparison-set rules, although inference changes with the rule; cross-validation selects zero latent factors in both four-case specifications. When Gabon and Qatar are included instead of Brazil, the corresponding five-case estimates are close to zero. Appendix Table \ref{tab:public-cue-pooled-ife} reports all four specifications. These pooled reduced forms combine the public cue with country-specific cost-benefit calculations, so the effects may be heterogeneous. The preserved pooled estimates also retain the report's 2009 Australian timing rather than re-estimating the pooled models with the new 2007 timing.

\begin{table}[H]
\centering
\caption{\label{tab:public-cue-pooled-ife}Pooled interactive fixed-effects estimates for Australia, Brazil, Chile, and Uruguay.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8.5}{10.5}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{llcccccc}
\toprule
Case sample & Comparison-set rule & ATT & SE & 95\% CI & p-value & Latent factors & Units (T/C)\\
\midrule
Four cases: AUS, BRA, CHL, URY & Never-China-top controls & -0.116 & 0.065 & {}[-0.244, 0.012] & 0.077 & 0 & 4/105\\
Four cases: AUS, BRA, CHL, URY & Controls enter and leave the comparison set & -0.136 & 0.066 & {}[-0.265, -0.007] & 0.038 & 0 & 4/152\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item ATT is measured in absolute UNGA ideal-point distance to China; negative values indicate convergence. Standard errors use 1,000 unit-bootstrap replications. The factor count is selected by the one-standard-error cross-validation rule over r = 0, 1, 2, 3. The preserved pooled models retain 2009 as Australia's timing; the individual Australian SDiD uses the theoretically preferred 2007 public-cue timing.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\section{Conclusion}\label{conclusion}

China's emergence as a major world power and its growing rivalry with the US have clear implications for countries' foreign policies toward China. A feature the literature has underappreciated concerns situations in which China's perceived or attributed status changes publicly and policymakers mobilize it to adjust or justify changes in their countries' foreign policies.

In this paper, we show that when China replaced the US as Brazil's top trading partner in 2009, Brazil shifted its foreign policy at the United Nations General Assembly toward China's positions. In the preferred statistical specification, the effect of entry into this trade-rank condition is a reduction of 0.273 ideal-point units in Brazil's distance to China relative to its counterfactual.

Brazilian evidence on the mechanism suggests that public recognition of this status in the media and its mobilization by policymakers are important in producing the observed outcome. I also show that the shift is not sudden and can occur selectively in particular issue areas where it will be visible to the new main partner and where there is an opportunity for closer alignment, as was the case for Brazil on human rights. This result is consistent with findings for a broader set of countries, although the magnitude is smaller. Cross-country estimates from the goods-only IFE model show a compatible directional pattern.

The paper therefore fills a gap in the literature on the effects of economic interdependence on foreign policy. Changes in rankings that are informationally redundant with trade statistics but still help coordinate expectations and justify a country's foreign policy may have an effect on their own.

Future research can extend the results in at least three directions. Firstly, research could expand to examine how the media in countries other than Brazil covered the change in ranking. The expectation is that, all else being equal, the more salient the change is in the media, the greater the adjustment in foreign policy. Second, it is necessary to connect these findings to how policymakers and political elites reacted to this change in status. It is conceivable that countries in which the reaction is negative may distance themselves from China, while those in which the reaction is positive may move closer. This is the theoretical expectation. Finally, researchers could apply a similar rank-threshold design to investment, aid, lending, or other economic ties where categorical milestones may become politically usable by the media and political elites.

\section*{Statements and Declarations}\label{statements-and-declarations}
\addcontentsline{toc}{section}{Statements and Declarations}

\subsection*{Funding}\label{funding}
\addcontentsline{toc}{subsection}{Funding}

Funding information is provided on the separate title page to preserve double anonymity.

\subsection*{Competing Interests}\label{competing-interests}
\addcontentsline{toc}{subsection}{Competing Interests}

The author has no relevant financial or non-financial interests to disclose.

\subsection*{Ethics Approval}\label{ethics-approval}
\addcontentsline{toc}{subsection}{Ethics Approval}

Not applicable. The study uses country-level observational data and publicly available documents and does not involve human participants or animals.

\subsection*{Data, Materials, and Code Availability}\label{data-materials-and-code-availability}
\addcontentsline{toc}{subsection}{Data, Materials, and Code Availability}

An anonymized replication archive can be supplied during peer review. The final data and code availability statement, including a stable repository link, will be updated before publication.

\subsection*{Author Contribution}\label{author-contribution}
\addcontentsline{toc}{subsection}{Author Contribution}

The sole author was responsible for all aspects of the work. Full contribution information is provided on the separate title page.

\clearpage

\bibliography{cpsr_references}

\clearpage

\appendix

\section*{Appendix}\label{appendix}
\addcontentsline{toc}{section}{Appendix}

The appendix reports the supporting diagnostics referenced in the main text: outcome and pre-trend series, resolution-level vote diagnostics, SDiD weights and donor-pool checks, the cross-country duration and sample audits, the ChatGPT classification and its validation, and the UNGA-DM measurement robustness.

\clearpage

\subsection*{Brazil and China Ideal-Point Series}\label{brazil-and-china-ideal-point-series}
\addcontentsline{toc}{subsection}{Brazil and China Ideal-Point Series}

Figure \ref{fig:appendix-brazil-china-ideal-points} plots the separate UNGA ideal-point series for Brazil and China. This diagnostic clarifies the interpretation of the absolute-distance outcome used in the main SDiD design: China's average position changes little around 2009 despite sizable year-to-year volatility, while Brazil shows a sustained post-2009 movement toward China.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:appendix-brazil-china-ideal-points}Brazil and China UNGA ideal-point series. The dashed line marks 2009. The figure separates the two series behind the absolute-distance outcome used in the main SDiD analysis. Note: UNGA ideal-point score (Bailey et al.~scale). Window: 1990-2022 annual series.}]{/Users/manoelgaldino/Documents/DCP/Papers/RDD Trade/red_trade/output/submission/cpsr/raw/cpsr_full_inline_anonymous_files/figure-latex/appendix-brazil-china-ideal-points-1.pdf}}
\caption{\label{fig:appendix-brazil-china-ideal-points}Brazil and China UNGA ideal-point series. The dashed line marks 2009. The figure separates the two series behind the absolute-distance outcome used in the main SDiD analysis. Note: UNGA ideal-point score (Bailey et al.~scale). Window: 1990-2022 annual series.}
\end{figure}

\clearpage

\subsection*{Triple-Difference Pre-Trends}\label{triple-difference-pre-trends}
\addcontentsline{toc}{subsection}{Triple-Difference Pre-Trends}

Figure \ref{fig:plot-ddd-pretrends} reports the input to the identification assumption behind the triple difference. Each series is Brazil's average distance to China minus its distance to the United States, net of the donor-pool average in the same year, computed separately for human-rights votes and for every other vote where China and the United States voted differently. What the triple difference requires is that these two series move together before treatment, so that any common drift cancels when one domain is differenced against the other.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:plot-ddd-pretrends}Brazil's distance from the donor pool in China-US divergent votes, by issue domain. Each point is Brazil's mean vote-level distance to China minus its distance to the United States, minus the donor-pool mean in the same year; more negative values mean Brazil sits closer to China than the donors do. The dashed line marks 2009. The two domains track each other before 2009 and separate afterward, which is the pattern the triple difference assumes and then estimates. Note: Vote-level distance to China minus distance to the United States, relative to the donor-pool mean. Window: 2005-2012 roll-call votes where China and the United States voted differently.}]{/Users/manoelgaldino/Documents/DCP/Papers/RDD Trade/red_trade/output/submission/cpsr/raw/cpsr_full_inline_anonymous_files/figure-latex/plot-ddd-pretrends-1.pdf}}
\caption{\label{fig:plot-ddd-pretrends}Brazil's distance from the donor pool in China-US divergent votes, by issue domain. Each point is Brazil's mean vote-level distance to China minus its distance to the United States, minus the donor-pool mean in the same year; more negative values mean Brazil sits closer to China than the donors do. The dashed line marks 2009. The two domains track each other before 2009 and separate afterward, which is the pattern the triple difference assumes and then estimates. Note: Vote-level distance to China minus distance to the United States, relative to the donor-pool mean. Window: 2005-2012 roll-call votes where China and the United States voted differently.}
\end{figure}

\clearpage

\subsection*{Resolution-Level UNGA Vote Diagnostics}\label{resolution-level-unga-vote-diagnostics}
\addcontentsline{toc}{subsection}{Resolution-Level UNGA Vote Diagnostics}

To make the Brazil-China movement in UNGA ideal points more concrete, Table \ref{tab:table-brazil-china-unvotes-year} reports the annual share of resolutions in which Brazil and China cast identical votes from 2005 to 2012. The diagnostic uses roll-call votes from \texttt{unvotes} 0.3.0, based on Erik Voeten's UNGA voting data, and excludes missing or absent votes by either Brazil or China.

\begin{table}[H]
\centering
\caption{\label{tab:table-brazil-china-unvotes-year}Brazil-China identical UNGA votes by year, 2005-2012.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{ccccc}
\toprule
Year & Resolutions & Identical votes & Identical votes (\textbackslash{}\%) & Mean similarity score\\
\midrule
2005 & 97 & 80 & 82.5 & 0.892\\
2006 & 108 & 88 & 81.5 & 0.884\\
2007 & 93 & 78 & 83.9 & 0.903\\
2008 & 96 & 73 & 76.0 & 0.859\\
2009 & 83 & 72 & 86.7 & 0.934\\
\addlinespace
2010 & 85 & 74 & 87.1 & 0.906\\
2011 & 96 & 83 & 86.5 & 0.927\\
2012 & 90 & 71 & 78.9 & 0.872\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Roll-call resolutions with valid Brazil and China votes; similarity score ranges from 0 to 1. Window: 2005-2012 annual series.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\clearpage

\subsection*{SDiD}\label{sdid}
\addcontentsline{toc}{subsection}{SDiD}

\subsubsection{Comparison of DiD, SCM, and SDiD Estimating Equations}\label{comparison-of-did-scm-and-sdid-estimating-equations}

To gain intuition for the SDiD estimator, it is useful to compare it with standard DiD and SCM. A DiD model estimates:

\[
\bigl(\hat{\tau}_{ATT}^{\text{DiD}}, \hat{\mu}, \hat{\alpha}, \hat{\beta}\bigr)
=
\operatorname*{arg\,min}_{\tau_{ATT},\mu, \alpha, \beta}
\sum_{i=1}^{N}\sum_{t=1}^{T}
\bigl(Y_{it}-\mu-\alpha_i -\beta_t-D_{it}\tau_{ATT}\bigr)^2
\]

Let \(N_0\) and \(N_1\) denote the numbers of control and treated units, and let \(T_0\) and \(T_1\) denote the numbers of pre- and post-treatment periods. Classic DiD corresponds to uniform weighting in this comparison. SDiD instead learns unit weights from pre-treatment outcome histories and assigns optimized weights to pre-treatment periods so that their weighted control-unit outcomes approximate the controls' average post-treatment outcomes. In the full unit-weight vector for each weighted estimator below, controls receive optimized nonnegative donor weights that sum to one, while each treated unit receives the fixed positive weight \(1/N_1\). In the full SDiD time-weight vector, optimized nonnegative pre-treatment weights sum to one, while each post-treatment period receives the fixed positive weight \(1/T_1\). Treated-post cells therefore enter the objectives with positive weight.

The SCM model can be written as follows:

\[
\bigl(\hat{\tau}_{ATT}^{\text{SCM}}, \hat{\mu}, \hat{\beta}\bigr)
=
\operatorname*{arg\,min}_{\tau_{ATT}, \mu, \beta}
\sum_{i=1}^{N}\sum_{t=1}^{T}
\hat{w}^{\text{SCM}}_i
\bigl(Y_{it}-\mu-\beta_t-D_{it}\tau_{ATT}\bigr)^2
\]

Here \(\hat{w}^{\text{SCM}}_i\) denotes the full unit-weight vector: optimized donor weights for controls and the fixed weight \(1/N_1\) for each treated unit. SCM uses the donor portion of this vector to match the treated unit's pre-treatment outcome path. SCM can approximate stable unit differences through donor weights when the treated unit lies in the donor convex hull, but it does not add unit fixed effects or optimized time weights. SDiD combines unit weights with unit fixed effects and time weights. The basic SDiD estimating equation is:

\[
\bigl(\hat{\tau}_{ATT}^{\text{SDiD}}, \hat{\mu}, \hat{\alpha}, \hat{\beta} \bigr)
=
\operatorname*{arg\,min}_{\tau_{ATT},\mu,\beta, \alpha}
\sum_{i=1}^{N}\sum_{t=1}^{T}
\hat{w}^{\text{SDiD}}_i \hat{\lambda}^{\text{SDiD}}_t
\bigl(Y_{it}- \mu- \alpha_i - \beta_t-D_{it}\tau_{ATT}\bigr)^2
\]

Note that SDiD retains unit fixed effects \(\alpha_i\) (like DiD) while also assigning unit weights \(\hat{w}^{\text{SDiD}}_i\) (like SCM) and time weights \(\hat{\lambda}^{\text{SDiD}}_t\) (unique to SDiD).

\subsubsection{SDiD Weights and Donor Pool}\label{sdid-weights-and-donor-pool}

Tables \ref{tab:sdid-unit-weights-complete}--\ref{tab:sdid-high-weight-donor-exposure} report the Brazil SDiD diagnostic package behind the compact summary in Table \ref{tab:brazil-sdid-diagnostic-summary}. I report the complete donor-weight vector rather than only the largest donors, all pre-treatment time weights, fit and balance diagnostics, rank-based placebo inference, donor-influence checks, window sensitivity, and donor exposure to China's export expansion.

\begingroup\fontsize{7}{9}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Weights sum to one over the donor pool; Brazil is excluded from the donor pool.
\end{TableNotes}
\begin{longtable}[t]{rllrr}
\caption{\label{tab:sdid-unit-weights-complete}Complete SDiD donor-unit weights for the Brazil synthetic counterfactual.}\\
\toprule
Rank & ISO3 & Donor & Weight & Cumulative weight\\
\midrule
1 & GEO & Georgia & 0.0313 & 0.0313\\
2 & SGP & Singapore & 0.0295 & 0.0608\\
3 & TCD & Chad & 0.0282 & 0.0890\\
4 & GTM & Guatemala & 0.0274 & 0.1164\\
5 & PRY & Paraguay & 0.0272 & 0.1436\\
\addlinespace
6 & BOL & Bolivia & 0.0226 & 0.1662\\
7 & ALB & Albania & 0.0221 & 0.1883\\
8 & COL & Colombia & 0.0221 & 0.2103\\
9 & DOM & Dominican Republic & 0.0218 & 0.2322\\
10 & IND & India & 0.0213 & 0.2534\\
\addlinespace
11 & AZE & Azerbaijan & 0.0210 & 0.2744\\
12 & TUR & Turkey & 0.0208 & 0.2953\\
13 & DEU & Germany & 0.0208 & 0.3160\\
14 & MWI & Malawi & 0.0182 & 0.3342\\
15 & CRI & Costa Rica & 0.0180 & 0.3522\\
\addlinespace
16 & FJI & Fiji & 0.0176 & 0.3698\\
17 & CYP & Cyprus & 0.0168 & 0.3866\\
18 & ARG & Argentina & 0.0164 & 0.4031\\
19 & PNG & Papua New Guinea & 0.0164 & 0.4194\\
20 & ISL & Iceland & 0.0162 & 0.4357\\
\addlinespace
21 & HTI & Haiti & 0.0158 & 0.4514\\
22 & HUN & Hungary & 0.0156 & 0.4670\\
23 & BRB & Barbados & 0.0155 & 0.4825\\
24 & KEN & Kenya & 0.0153 & 0.4978\\
25 & NOR & Norway & 0.0151 & 0.5129\\
\addlinespace
26 & SUR & Suriname & 0.0150 & 0.5279\\
27 & TTO & Trinidad \& Tobago & 0.0146 & 0.5424\\
28 & DNK & Denmark & 0.0141 & 0.5566\\
29 & LTU & Lithuania & 0.0137 & 0.5703\\
30 & NIC & Nicaragua & 0.0137 & 0.5840\\
\addlinespace
31 & HRV & Croatia & 0.0137 & 0.5977\\
32 & POL & Poland & 0.0136 & 0.6113\\
33 & SLV & El Salvador & 0.0133 & 0.6246\\
34 & TUN & Tunisia & 0.0132 & 0.6379\\
35 & EST & Estonia & 0.0132 & 0.6511\\
\addlinespace
36 & PAK & Pakistan & 0.0129 & 0.6640\\
37 & JAM & Jamaica & 0.0126 & 0.6765\\
38 & MDV & Maldives & 0.0121 & 0.6886\\
39 & TGO & Togo & 0.0118 & 0.7004\\
40 & LVA & Latvia & 0.0114 & 0.7118\\
\addlinespace
41 & ESP & Spain & 0.0111 & 0.7229\\
42 & LBN & Lebanon & 0.0109 & 0.7338\\
43 & SVN & Slovenia & 0.0108 & 0.7446\\
44 & MUS & Mauritius & 0.0108 & 0.7554\\
45 & DZA & Algeria & 0.0108 & 0.7662\\
\addlinespace
46 & ROU & Romania & 0.0105 & 0.7767\\
47 & BGR & Bulgaria & 0.0105 & 0.7872\\
48 & GUY & Guyana & 0.0103 & 0.7975\\
49 & CZE & Czechia & 0.0101 & 0.8076\\
50 & AUT & Austria & 0.0101 & 0.8177\\
\addlinespace
51 & JOR & Jordan & 0.0098 & 0.8275\\
52 & QAT & Qatar & 0.0097 & 0.8372\\
53 & SWE & Sweden & 0.0093 & 0.8465\\
54 & NAM & Namibia & 0.0092 & 0.8557\\
55 & PAN & Panama & 0.0091 & 0.8648\\
\addlinespace
56 & FIN & Finland & 0.0089 & 0.8737\\
57 & NLD & Netherlands & 0.0089 & 0.8826\\
58 & COM & Comoros & 0.0089 & 0.8915\\
59 & SEN & Senegal & 0.0088 & 0.9003\\
60 & ISR & Israel & 0.0085 & 0.9088\\
\addlinespace
61 & GRC & Greece & 0.0085 & 0.9173\\
62 & UGA & Uganda & 0.0081 & 0.9254\\
63 & PRT & Portugal & 0.0081 & 0.9335\\
64 & SVK & Slovakia & 0.0078 & 0.9413\\
65 & MDA & Moldova & 0.0077 & 0.9490\\
\addlinespace
66 & ITA & Italy & 0.0077 & 0.9567\\
67 & MAR & Morocco & 0.0071 & 0.9638\\
68 & BTN & Bhutan & 0.0062 & 0.9700\\
69 & GBR & United Kingdom & 0.0061 & 0.9760\\
70 & USA & United States & 0.0045 & 0.9806\\
\addlinespace
71 & CAN & Canada & 0.0040 & 0.9845\\
72 & LKA & Sri Lanka & 0.0040 & 0.9885\\
73 & BWA & Botswana & 0.0036 & 0.9921\\
74 & IRL & Ireland & 0.0032 & 0.9952\\
75 & LBY & Libya & 0.0021 & 0.9973\\
\addlinespace
76 & UKR & Ukraine & 0.0009 & 0.9983\\
77 & FRA & France & 0.0009 & 0.9992\\
78 & ARE & United Arab Emirates & 0.0004 & 0.9996\\
79 & BGD & Bangladesh & 0.0004 & 0.9999\\
80 & EGY & Egypt & 0.0000 & 1.0000\\
\addlinespace
81 & MEX & Mexico & 0.0000 & 1.0000\\
82 & BHR & Bahrain & 0.0000 & 1.0000\\
83 & BLR & Belarus & 0.0000 & 1.0000\\
84 & CIV & Côte d’Ivoire & 0.0000 & 1.0000\\
85 & CPV & Cape Verde & 0.0000 & 1.0000\\
\addlinespace
86 & ECU & Ecuador & 0.0000 & 1.0000\\
87 & GAB & Gabon & 0.0000 & 1.0000\\
88 & GHA & Ghana & 0.0000 & 1.0000\\
89 & GIN & Guinea & 0.0000 & 1.0000\\
90 & KWT & Kuwait & 0.0000 & 1.0000\\
\addlinespace
91 & MDG & Madagascar & 0.0000 & 1.0000\\
92 & NGA & Nigeria & 0.0000 & 1.0000\\
93 & RWA & Rwanda & 0.0000 & 1.0000\\
94 & SWZ & Eswatini & 0.0000 & 1.0000\\
95 & VEN & Venezuela & 0.0000 & 1.0000\\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}
\endgroup{}

\begin{table}[H]
\centering
\caption{\label{tab:sdid-time-weights}SDiD pre-treatment time weights for the preferred Brazil specification.}
\centering
\fontsize{8}{10}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{rrrr}
\toprule
Year & Time weight & Weight rank & High weight\\
\midrule
1997 & 0.0000 & 8 & No\\
1998 & 0.0248 & 6 & No\\
1999 & 0.0979 & 4 & No\\
2000 & 0.0000 & 8 & No\\
2001 & 0.0000 & 8 & No\\
\addlinespace
2002 & 0.0000 & 8 & No\\
2003 & 0.0000 & 8 & No\\
2004 & 0.0150 & 7 & No\\
2005 & 0.0807 & 5 & No\\
2006 & 0.1282 & 3 & Yes\\
\addlinespace
2007 & 0.3020 & 2 & Yes\\
2008 & 0.3515 & 1 & Yes\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item The weights are assigned over the 1997-2008 pre-treatment period.
\end{tablenotes}
\end{threeparttable}
\end{table}

\begin{table}[H]
\centering
\caption{\label{tab:sdid-prefit-summary}Intercept-adjusted pre-treatment fit summary for the preferred Brazil SDiD specification.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8}{10}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lrrrrrrr}
\toprule
Specification & ATT & Placebo SE & Adj. pre RMSPE & Adj. post RMSPE & Post/pre adj. RMSPE & Pre-treatment mean & \% of pre-mean\\
\midrule
Preferred: no covariates & -0.273 & 0.131 & 0.058 & 0.320 & 5.544 & 0.647 & -42.2\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item ATT is the estimated average causal effect on Brazil after 2009, in absolute UNGA ideal-point distance to China. RMSPE diagnostics subtract the mean pre-treatment gap between Brazil and its synthetic comparison before computing RMSPE, reflecting SDiD's allowance for stable level differences.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\begingroup\fontsize{7}{9}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item The preferred specification uses no covariates; these variables are reported as descriptive pre-treatment comparisons only. Synthetic values use the SDiD unit weights and are not residualized synthdid balance statistics.
\end{TableNotes}
\begin{longtable}[t]{llrrrr}
\caption{\label{tab:sdid-balance}Pre-treatment outcome balance and fixed values supplied in the preferred SDiD audit.}\\
\toprule
Variable & Definition & Brazil pre-mean & Synthetic pre-mean & Difference & Std. difference\\
\midrule
abs\_distance\_china & 1997-2008 mean & 0.647 & 0.987 & -0.340 & -0.432\\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}
\endgroup{}

\begin{table}[H]
\centering
\caption{\label{tab:sdid-placebo-rank}Directional and bilateral placebo-in-space rank inference for the preferred Brazil SDiD estimate.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{7}{9}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lcccccl}
\toprule
Comparison set & Directional rank & Directional p & Absolute rank & Bilateral p & Denominator & Note\\
\midrule
All valid assignments & 3/96 & 0.031 & 7/96 & 0.073 & 96 & Primary rank comparison\\
Pre-fit RMSPE no larger than twice Brazil & 2/70 & 0.029 & 4/70 & 0.057 & 70 & Fit-filter sensitivity; not used to select the main p-value\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item The primary distribution includes Brazil and all valid placebo-in-space assignments. The directional rank tests the theory-aligned direction of convergence; the bilateral absolute rank is the conservative two-sided counterpart. Interpreting these ranks as p-values requires sufficiently comparable placebo assignments; the donor exposure audit and the pre-fit filter probe, but cannot guarantee, that condition. The fit-filter row was not used to choose the main result.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\begingroup\fontsize{7}{9}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Placebo SEs are not recomputed for donor-deletion rows; those rows are point-estimate and intercept-adjusted fit diagnostics.
\end{TableNotes}
\begin{longtable}[t]{lrrrrrl}
\caption{\label{tab:sdid-donor-sensitivity}Sensitivity to influential donors and high-weight donor blocks.}\\
\toprule
Specification & ATT & Adj. pre RMSPE & Post/pre adj. RMSPE & Removed donors & \% change & Inference\\
\midrule
Preferred: no covariates & -0.273 & 0.058 & 5.544 & 0 & 0.0 & Main SE and rank reported separately\\
Drop Georgia (rank 1) & -0.270 & 0.060 & 5.318 & 1 & 1.1 & Point estimate only\\
Drop Singapore (rank 2) & -0.275 & 0.060 & 5.427 & 1 & -1.0 & Point estimate only\\
Drop Chad (rank 3) & -0.272 & 0.060 & 5.339 & 1 & 0.3 & Point estimate only\\
Drop Guatemala (rank 4) & -0.277 & 0.059 & 5.453 & 1 & -1.6 & Point estimate only\\
\addlinespace
Drop Paraguay (rank 5) & -0.274 & 0.059 & 5.412 & 1 & -0.3 & Point estimate only\\
Drop Bolivia (rank 6) & -0.263 & 0.058 & 5.423 & 1 & 3.6 & Point estimate only\\
Drop Albania (rank 7) & -0.274 & 0.058 & 5.537 & 1 & -0.5 & Point estimate only\\
Drop Colombia (rank 8) & -0.270 & 0.059 & 5.357 & 1 & 1.2 & Point estimate only\\
Drop Dominican Republic (rank 9) & -0.276 & 0.058 & 5.592 & 1 & -1.0 & Point estimate only\\
\addlinespace
Drop India (rank 10) & -0.273 & 0.059 & 5.496 & 1 & -0.2 & Point estimate only\\
Drop top 10 donors by weight & -0.268 & 0.074 & 4.395 & 10 & 1.6 & Point estimate only\\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}
\endgroup{}

\begin{table}[H]
\centering
\caption{\label{tab:sdid-window-sensitivity}Sensitivity to plausible time windows around the preferred 1997-2015 specification.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8}{10}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lrrrrl}
\toprule
Window & ATT & Adj. pre RMSPE & Post/pre adj. RMSPE & \% change & Inference\\
\midrule
1997-2013 & -0.294 & 0.056 & 5.610 & -7.8 & Point estimate only\\
1997-2014 & -0.320 & 0.057 & 6.066 & -17.5 & Point estimate only\\
1997-2015 preferred & -0.273 & 0.058 & 5.544 & 0.0 & 20,000-placebo SE and rank reported in main results\\
1997-2016 & -0.278 & 0.059 & 5.624 & -1.8 & Point estimate only\\
1998-2015 & -0.256 & 0.039 & 8.151 & 6.2 & Point estimate only\\
\addlinespace
1999-2015 & -0.267 & 0.027 & 11.976 & 1.9 & Point estimate only\\
2000-2015 & -0.265 & 0.028 & 11.343 & 2.9 & Point estimate only\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item The preferred 1997-2015 row uses the placebo SE and rank inference reported in the main results. Other windows are point-estimate and intercept-adjusted fit diagnostics; their placebo distributions were not recomputed.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\begin{table}[H]
\centering
\caption{\label{tab:sdid-high-weight-donor-exposure}High-weight donor exposure to China in exports of goods and services.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8}{10}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{rllrrrrl}
\toprule
Rank & ISO3 & Donor & Weight & China share pre & China share post & Best post rank & Flag\\
\midrule
1 & GEO & Georgia & 0.031 & 0.006 & 0.013 & 14 & No top-two China export-destination exposure\\
2 & SGP & Singapore & 0.029 & 0.072 & 0.112 & 1 & China top export destination post-2009\\
3 & TCD & Chad & 0.028 & 0.038 & 0.061 & 2 & China top-two export destination post-2009\\
4 & GTM & Guatemala & 0.027 & 0.003 & 0.007 & 11 & No top-two China export-destination exposure\\
5 & PRY & Paraguay & 0.027 & 0.007 & 0.006 & 21 & No top-two China export-destination exposure\\
\addlinespace
6 & BOL & Bolivia & 0.023 & 0.009 & 0.033 & 4 & No top-two China export-destination exposure\\
7 & ALB & Albania & 0.022 & 0.012 & 0.067 & 2 & China top-two export destination post-2009\\
8 & COL & Colombia & 0.022 & 0.008 & 0.056 & 2 & China top-two export destination post-2009\\
9 & DOM & Dominican Republic & 0.022 & 0.004 & 0.021 & 3 & No top-two China export-destination exposure\\
10 & IND & India & 0.021 & 0.049 & 0.060 & 3 & No top-two China export-destination exposure\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item High-weight donors are the ten donors with the largest SDiD unit weights. China shares and destination ranks in this table include goods and services. Pre and post refer to 1997--2008 and 2009--2015, respectively; shares are annual averages within each window. Best post rank is China's highest export-destination position attained during 2009--2015. Donor eligibility instead uses goods-only ranks: no donor had China as its largest goods-export destination during 1997--2015. Among these high-weight donors, 1 had China as the top export destination in goods and services during 2009--2015 and 4 were cases where China ranked in the top two, accounting for 10.2 percent of total SDiD weight.
\end{tablenotes}
\end{threeparttable}}
\end{table}

Below I also present the ten largest donor weights used in the main model as a visual summary.

\begin{figure}[H]
\includegraphics[width=0.9\linewidth]{quality_reports/china_demand_shock_rank_threshold/figure_brazil_sdid_predetermined_core_weights} \caption{Ten largest donor weights contributing to the synthetic control in the Brazilian SDiD model. Note: Synthetic-control unit weights, normalized over the full donor pool rather than only over the displayed donors. Window: pre-treatment period ending in 2008.}\label{fig:plot-weights}
\end{figure}

I also fit a model for a donor pool of Latin American states (excluding Caribbean countries), which is substantively attractive because the donor countries are regionally closer to Brazil. This regional donor pool is a sensitivity check rather than the preferred specification: the main design seeks a pre-treatment synthetic counterfactual with adequate donor support and fit, while the Latin American pool is much smaller.

\begin{figure}[H]
\includegraphics[width=0.95\linewidth]{quality_reports/china_demand_shock_rank_threshold/figure_brazil_sdid_predetermined_core_latam_fit} \caption{SDiD fit with a Latin American donor pool, estimated without covariates. Note: Absolute UNGA ideal-point distance to China. SE: 0.207 (placebo, 20,000 replications). Window: 1997-2015 annual series.}\label{fig:plot-latam}
\end{figure}

Estimated without covariates, the Latin America donor-pool estimate has the same sign and a somewhat larger magnitude: -0.326, compared with -0.273 in the global donor pool. The regional pool has only 19 donors and a slightly higher intercept-adjusted pre-treatment RMSPE (0.069 versus 0.058). Its placebo SE is 0.207, based on 20,000 replications, and the normal-approximation 95 percent interval {[}-0.731, 0.080{]} includes zero. Because the directional placebo comparison is computed within this regional pool, which contains only 19 donor units, even Brazil being the 2nd most negative among all 20 assignments yields a p-value of only 0.100. In other words, the regional donor pool does not provide enough power to estimate the effect precisely. The point estimate is nevertheless consistent with the main result and, if anything, is somewhat larger in absolute value than the estimate from the larger global donor pool.

\clearpage

\subsection*{Selected Public-Cue Cross-Country Analyses}\label{selected-public-cue-cross-country-analyses}
\addcontentsline{toc}{subsection}{Selected Public-Cue Cross-Country Analyses}

This section reports the diagnostics underlying the proposed replacement for the cross-country section. The common country-year window is 1997--2022, and the outcome is absolute UNGA ideal-point distance to China. The individual SDiD models use 105 countries that never have China as their largest goods-export destination during this window. Each individual estimate uses a placebo standard error from 5,000 re-estimations. The pooled models use the interactive fixed-effects estimator in \texttt{fect} 2.4.5, with the number of latent factors selected by cross-validation and 1,000 unit-bootstrap replications.

Figure \ref{fig:public-cue-pre-treatment-distance} compares the focal cases before their selected public-cue years. Gabon has the smallest mean pre-cue distance to China among the five cases (0.182), which motivates treating its limited room for further convergence as a scope consideration rather than interpreting its exclusion as evidence that no cue occurred.

\begin{figure}[H]
\includegraphics[width=0.95\linewidth]{quality_reports/revisions/paper_v4/20260922_cross_country_public_cue_preview/assets/figure_pre_cue_distance_focal_cases} \caption{Pre-cue UNGA ideal-point distance to China among the five focal public-cue cases. Solid points and labels show country-specific means; hollow points show medians; horizontal segments span the observed pre-cue range. Each pre-period runs from 1997 through the year before the selected cue, so the number of years differs across countries. Lower values indicate positions closer to China.}\label{fig:public-cue-pre-treatment-distance}
\end{figure}

Table \ref{tab:public-cue-sdid-results} reports the individual estimates discussed in the proposed text. Australia 2007 is the theoretically preferred public-cue timing, while Australia 2010 is a robustness timing based on entry into the top goods-export-destination position. For every row, the p-value is the two-sided normal approximation constructed from the placebo standard error; it is not an exact randomization p-value.

\begin{table}[H]
\centering
\caption{\label{tab:public-cue-sdid-results}Individual SDiD estimates for the public-cue cases retained in the proposed cross-country section.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8.5}{10.5}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{llcccccc}
\toprule
Country & Timing & ATT & SE & 95\% CI & p-value & Pre/Post & Donors\\
\midrule
Chile & Public cue (2008) & -0.130 & 0.154 & {}[-0.433, 0.173] & 0.400 & 11/15 & 105\\
Uruguay & Public cue (2013) & -0.068 & 0.151 & {}[-0.365, 0.229] & 0.652 & 16/10 & 105\\
Australia & Public cue (2007) & 0.128 & 0.161 & {}[-0.187, 0.444] & 0.424 & 10/16 & 105\\
Australia & Top goods-export destination (2010) & 0.090 & 0.147 & {}[-0.198, 0.378] & 0.540 & 13/13 & 105\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item ATT is measured in absolute UNGA ideal-point distance to China; negative values indicate convergence. Every row uses a placebo standard error from 5,000 re-estimations. Confidence intervals and two-sided p-values use a normal approximation based on the placebo standard error; the p-values are not exact randomization p-values.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\clearpage

\subsection*{Cross-Country Robustness: Duration Thresholds}\label{cross-country-robustness-duration-thresholds}
\addcontentsline{toc}{subsection}{Cross-Country Robustness: Duration Thresholds}

The main cross-country estimate uses a five-year durability threshold because the theory concerns status that persists long enough to become politically usable. Table \ref{tab:cross-country-duration-table} reports the same goods-only IFE design under three- and seven-year thresholds, along with the clean single-entry robustness sample. The estimates remain negative across the restricted-risk-set rows, though precision varies with treated-unit support.

\begin{table}[H]
\centering
\caption{\label{tab:cross-country-duration-table}Duration-threshold robustness for goods-only China top export-destination status.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{7}{9}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{llccccccc}
\toprule
Minimum duration & Specification & ATT & SE & 95\% CI & p-value & Units (T/C) & Treated periods & r*\\
\midrule
3 & Status-current, restricted risk set & -0.113 & 0.041 & {}[-0.193, -0.034] & 0.005 & 39/126 & 477 & 2\\
3 & Clean single-entry robustness & -0.121 & 0.041 & {}[-0.202, -0.040] & 0.003 & 26/126 & 332 & 2\\
5 & Status-current, restricted risk set & -0.101 & 0.039 & {}[-0.177, -0.024] & 0.010 & 35/126 & 440 & 2\\
5 & Clean single-entry robustness & -0.122 & 0.041 & {}[-0.202, -0.042] & 0.003 & 25/126 & 329 & 2\\
7 & Status-current, restricted risk set & -0.094 & 0.040 & {}[-0.173, -0.016] & 0.019 & 31/126 & 411 & 2\\
\addlinespace
7 & Clean single-entry robustness & -0.122 & 0.042 & {}[-0.205, -0.039] & 0.004 & 23/126 & 318 & 2\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item ATT in absolute UNGA ideal-point distance to China; lower values indicate convergence toward China. SE: bootstrap with 10,000 replications. Window: goods-only ITPD-E rank metric. The restricted-risk-set rows retain clean pre-entry non-China-top years and qualifying treated years. The clean single-entry rows additionally keep only treated countries with one observed qualifying China-top period.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\clearpage

\subsection*{Cross-Country Sample Audit: Goods-Only Treatment Coding}\label{cross-country-sample-audit-goods-only-treatment-coding}
\addcontentsline{toc}{subsection}{Cross-Country Sample Audit: Goods-Only Treatment Coding}

The revised rank metric excludes services before partner ranks are computed. Table \ref{tab:cross-country-sector-table} documents the ITPD-E broad-sector filter. Table \ref{tab:cross-country-audit-table} then summarizes how the five-year goods-only rule classifies countries in the UNGA/trade panel.

\begin{table}[H]
\centering
\caption{\label{tab:cross-country-sector-table}ITPD-E sector filter used to construct the goods-only China top export-destination metric.}
\centering
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{lrrl}
\toprule
Broad sector & Raw rows & Positive-trade rows & Included in rank metric\\
\midrule
Agriculture & 7331458 & 2484549 & Yes\\
Manufacturing & 71208330 & 28203707 & Yes\\
Mining and Energy & 1205032 & 416413 & Yes\\
Services & 1002558 & 519520 & No\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}[H]
\centering
\caption{\label{tab:cross-country-audit-table}Country-level sample audit for the five-year goods-only China top export-destination rule.}
\centering
\fontsize{8}{10}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lr}
\toprule
Role & Countries\\
\midrule
Excluded: no clean observed prior non-China-top year & 1\\
Excluded: pre-2000 China-top entry & 2\\
Excluded: short China-top periods & 26\\
Never-China-top controls & 128\\
Qualifying treated countries & 35\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item The audit uses the goods-only rank metric and classifies countries before the estimator-specific screen for minimum untreated support. Country counts are therefore a coding audit, not a replacement for the treated/control counts in the estimation table.
\end{tablenotes}
\end{threeparttable}
\end{table}

\clearpage

\subsection*{Public Cue and Recoverability Audit}\label{public-cue-and-recoverability-audit}
\addcontentsline{toc}{subsection}{Public Cue and Recoverability Audit}

To assess how closely the empirical treatment used in the panel regression -- China becoming a country's largest destination for goods exports -- maps onto the theorized treatment of a publicly salient status change, I use a source audit originally constructed for 14 countries in an earlier no-covariate treated sample. This audit is not a census of the 35 countries treated in the current goods-only restricted-risk-set specification: 13 audited countries remain in the current treated sample, Qatar does not, and 22 current treated countries were not included in the source audit. The underlying matrix records both recovered and unrecovered China cues. Table \ref{tab:ex-top1-recoverability-audit} displays the nine cases in which the China cue is currently coded as unknown; Chile, Brazil, Uruguay, Saudi Arabia, and Qatar have recovered cues and are omitted by the display filter.

The table distinguishes weak observation from cases in which public rank language about the displaced incumbent is recoverable. For the China cue, \texttt{medium} means one countable strong or moderate first-window source with explicit rank language. For the former-incumbent benchmark, \texttt{medium} means either one countable source with explicit incumbent-rank or displacement language, or at least two countable trade-coverage records from at least one independent source without a clear top-rank label. A countable source must be eligible, fall within one year of the source-audit entry year, be coded strong or moderate, enter the benchmark, and not be marked \texttt{DO\_NOT\_COUNT}. \texttt{Unknown} means that the incumbent was not identified or that no countable benchmark source was recovered; no case is currently coded \texttt{low}. Non-recovery is not evidence that a cue was absent because contemporaneous local or official records may be inaccessible or inconsistent with the trade-rank series. Except for Australia, whose displayed year has been reconciled to the current 2009 entry, the table retains the entry windows used in the legacy source audit. Table \ref{tab:ex-top1-australia-afr-context} reports Australia's broad-trade source separately.

\begingroup\fontsize{7}{9}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Nine unresolved cases from a 14-country legacy audit; this is not a census of the current treated sample. Definitions and the display filter are reported in the text. Australia's entry year follows the current goods-only annual panel; other entry windows remain those of the legacy audit.
\end{TableNotes}
\begin{longtable}[t]{lrll>{\raggedright\arraybackslash}p{4.0cm}>{\raggedright\arraybackslash}p{4.2cm}}
\caption{\label{tab:ex-top1-recoverability-audit}Selected unresolved cases from a 14-country legacy source audit of public rank-language recoverability and metric caveats.}\\
\toprule
Country & Entry year & China cue & Ex-\#1 benchmark & Interpretation & Caveat\\
\midrule
Solomon Islands & 2003 & unknown & unknown & Weak observation/recoverability problem & Additional local/official archive work required.\\
Philippines & 2005 & unknown & unknown & Weak observation/recoverability problem & Treatment-rank audit issue in contemporaneous sources.\\
Angola & 2007 & unknown & unknown & Weak observation/recoverability problem & Additional local/official archive work required.\\
Malaysia & 2009 & unknown & medium & Benchmark recoverable; follow up before recoding salience & Rank-definition and China/Hong Kong aggregation caveat.\\
Sierra Leone & 2012 & unknown & unknown & Weak observation/recoverability problem & Local statistics conflict with Belgium-as-incumbent.\\
\addlinespace
Myanmar (Burma) & 2014 & unknown & unknown & Weak observation/recoverability problem & Additional local/official archive work required.\\
Saudi Arabia & 2013 & unknown & unknown & Weak observation/recoverability problem & Corrected 2013-2014 public-cue window remains unresolved; rank-definition reconciliation is required.\\
Kuwait & 2018 & unknown & unknown & Weak observation/recoverability problem & Additional local/official archive work required.\\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}
\endgroup{}

\begin{table}[H]
\centering
\caption{\label{tab:ex-top1-australia-afr-context}Australian Financial Review context source for Australia.}
\centering
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{4.6cm}>{\raggedright\arraybackslash}p{10.0cm}}
\toprule
\textbf{Source} & Australian Financial Review\\
\textbf{Date} & 2009-11-09\\
\textbf{Metric} & Australia's largest aggregate trading partner\\
\textbf{Counted in export-destination benchmark} & No\\
\textbf{Raw file} & \texttt{data/\allowbreak{}raw/\allowbreak{}ex\_top1\_salience/\allowbreak{}AUS/\allowbreak{}2009/\allowbreak{}australian\_financial\_review/\allowbreak{}aus\_afr\_china\_trading\_partner\_2009.html}\\
\textbf{Interpretation} & Counts for broad public-cue salience in the current 2009 treatment window; remains excluded from the strict export-destination benchmark because the metric combines exports and imports of goods and services.\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item The AFR item documents a broad aggregate-trading-partner cue. It documents broad-metric salience during the 2009 annual treatment window. The publication date does not establish that a strict goods-export cue preceded treatment.
\end{tablenotes}
\end{threeparttable}
\end{table}

\clearpage

\clearpage

\subsection*{ChatGPT Classification}\label{chatgpt-classification}
\addcontentsline{toc}{subsection}{ChatGPT Classification}

Below is the coded instruction to the ChatGPT API to classify the subjects of the headlines.

\begingroup\singlespacing

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{system\_block }\OtherTok{\textless{}{-}} \FunctionTok{paste}\NormalTok{(}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}You are a Brazilian expert in International Relations and \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}the political\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}economy of China–Brazil relations.  Classify the subject \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}of EACH headline\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}when I say EACH, I mean all of them, even if repetitive or \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}similar. Do classify **all** of them\textquotesingle{}}
\NormalTok{  ),}
  \StringTok{\textquotesingle{}using **one** label from this list exactly as written:\textquotesingle{}}\NormalTok{,}
  \StringTok{\textquotesingle{}"diplomacy", "chinese economy", "china{-}brasil relations",\textquotesingle{}}\NormalTok{,}
  \StringTok{\textquotesingle{}"disaster and accidents", "chinese politics and policy",\textquotesingle{}}\NormalTok{,}
  \StringTok{\textquotesingle{}"sports, science, culture, other", "human rights",\textquotesingle{}}\NormalTok{,}
  \StringTok{\textquotesingle{}"china{-}brazil trade", "health".}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{,}
  \CommentTok{\# 13 static few{-}shot examples — leave them unchanged!}
  \StringTok{\textquotesingle{}Examples:}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{,}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}1. Presidente chinês visita o Brasil e participa de \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}reunião com FHC {-}\textgreater{} china{-}brasil relations}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}2. Ministro chinês de Defesa faz visita oficial ao Brasil \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}{-}\textgreater{} china{-}brasil relations}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}3. Para governo, novo câmbio chinês só beneficia Brasil no \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}médio prazo {-}\textgreater{} china{-}brazil trade}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}4. China ultrapassa EUA como maior parceiro comercial do \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}Brasil {-}\textgreater{} china{-}brazil trade}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}5. China vai controlar preços de alimentos e combustíveis \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}{-}\textgreater{} chinese economy}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}6. Vendas de automóveis na China desaceleram em junho {-}\textgreater{} \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}chinese economy}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}7. China quer devolução das relíquias Yin, patrimônio da \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}Unesco {-}\textgreater{} sports, science, culture, other}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}8. Dinossauro encontrado na China esclarece origem das \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}aves {-}\textgreater{} sports, science, culture, other}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}9. OMS confirma mais de 4.600 casos de gripe suína; China \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}registra 2º caso {-}\textgreater{} health}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}10. Marinha chinesa busca "cansar" barcos japoneses em \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}águas disputadas {-}\textgreater{} diplomacy}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}11. Acidente após casamento deixa 16 mortos na China {-}\textgreater{} \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}disaster and accidents}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}12. Jornal chinês sai das bancas por foto da praça \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}Tiananmen {-}\textgreater{} human rights}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}13. China é parceira estratégica contra crise econômica, \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}diz UE {-}\textgreater{} chinese economy\textquotesingle{}}
\NormalTok{  ),}
  \FunctionTok{paste0}\NormalTok{(}
    \StringTok{\textquotesingle{}return as in the examples, a string with the headline and \textquotesingle{}}\NormalTok{,}
    \StringTok{\textquotesingle{}the classification\textquotesingle{}}
\NormalTok{  )}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\endgroup

The classified headline file is an archived derived dataset and is not regenerated during manuscript rendering. The preserved producer specifies the OpenAI API model alias \texttt{gpt-4.1-mini} with temperature set to zero. It deduplicates the retrieved headlines, retains titles containing \texttt{China}, \texttt{chinês}, or \texttt{chinesa}, divides them into code-defined 500-row slices, opens a new chat object for each slice, splits returned text by line and \texttt{-\textgreater{}}, removes numeric prefixes, joins classifications back by exact headline text, and normalizes the label string \texttt{china-brasil\ relations} to \texttt{china-brazil\ relations}. These statements document the preserved code configuration, not the exact historical execution that produced every archived row. The archived file is frozen as the analysis input and records the configured model alias, but the archive does not preserve an immutable model snapshot, a complete request-and-response log, the exact history or rules of manual reruns, or values for generation parameters left at provider defaults. It therefore permits auditing of the stored corpus and code configuration, but not exact re-execution of the historical API calls. The evidence in the main text is used as a headline-level salience diagnostic.

Below I reproduce the 14 archived headline examples and their ChatGPT classifications.

\begin{figure}[H]
\includegraphics[width=\linewidth]{images/RIO_20260905_table1_headlines_14} \caption{Fourteen archived examples of China-related Folha de S.Paulo headlines and ChatGPT classifications. Note: headline text and category labels. Window: sample drawn from the 2000-2014 corpus.}\label{fig:sample-chatgpt}
\end{figure}

\subsubsection{Validation of ChatGPT Classification}\label{validation-of-chatgpt-classification}

To assess the archived classification, I manually coded a stratified random sample of 100 headlines, allocated in proportion to the sizes of the automated-label categories in the full corpus, with a minimum of five cases per category. The random seed used to select the sample was not retained. Table \ref{tab:chatgpt-validation} reports accuracy against manual coding.

\begin{table}[H]
\centering
\caption{\label{tab:chatgpt-validation}Accuracy of archived model labels against manual coding in the stratified random validation sample (N = 100). Overall sample accuracy: 88.0 percent.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lccc}
\toprule
Predicted label & N & Agreements & Agreement within predicted-label sample (\textbackslash{}\%)\\
\midrule
china-brazil trade & 6 & 6 & 100.0\\
disaster and accidents & 13 & 13 & 100.0\\
health & 6 & 6 & 100.0\\
chinese economy & 25 & 24 & 96.0\\
human rights & 8 & 7 & 87.5\\
\addlinespace
diplomacy & 12 & 10 & 83.3\\
sports, science, culture, other & 17 & 14 & 82.4\\
china-brazil relations & 5 & 4 & 80.0\\
chinese politics and policy & 8 & 4 & 50.0\\
Overall & 100 & 88 & 88.0\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item headline-level counts and accuracy by archived predicted label. Window: stratified random validation sample from the 2000-2014 headline corpus.
\end{tablenotes}
\end{threeparttable}}
\end{table}

Overall accuracy in the validation sample is 88.0 percent. The lowest agreement is in the ``chinese politics and policy'' category (50.0 percent), where several headlines were manually reclassified as ``diplomacy.'' The category most central to the mechanism, ``china-brazil trade,'' has 100.0 percent agreement among sampled headlines carrying that automated label. The corresponding rates are 80.0 percent for ``china-brazil relations'' and 83.3 percent for ``diplomacy.'' Because the table rows condition on the archived predicted label, the category-specific rates measure precision rather than recall. This validation does not assess whether classification error changed over 2000--2014. Figure \ref{fig:plot-media-counterfactual} should therefore be read as a descriptive summary of the archived labels subject to classification error.

\clearpage

\subsection*{Cross-Country: Goods-Only Treated Countries}\label{cross-country-goods-only-treated-countries}
\addcontentsline{toc}{subsection}{Cross-Country: Goods-Only Treated Countries}

Table \ref{tab:table-treated-appendix} describes the 35 treated countries in the main goods-only restricted-risk-set specification. For each country, the table reports the first qualifying China-top goods-export year and the number of treated and untreated country-years retained in the estimation panel.

\begin{table}[!h]
\centering
\caption{\label{tab:table-treated-appendix}Treated countries in the main goods-only restricted-risk-set cross-country specification.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{llccccc}
\toprule
Country & ISO3c & Treatment year & Treated years & Pre/other untreated years & First panel year & Last panel year\\
\midrule
Sudan & SDN & 2000 & 6 & 10 & 1990 & 2005\\
Solomon Islands & SLB & 2003 & 20 & 13 & 1990 & 2022\\
South Korea & KOR & 2003 & 20 & 12 & 1991 & 2022\\
Cuba & CUB & 2004 & 18 & 14 & 1990 & 2022\\
Oman & OMN & 2004 & 19 & 13 & 1990 & 2022\\
\addlinespace
Philippines & PHL & 2005 & 18 & 15 & 1990 & 2022\\
Yemen & YEM & 2005 & 11 & 13 & 1991 & 2015\\
Mauritania & MRT & 2006 & 17 & 15 & 1990 & 2022\\
Angola & AGO & 2007 & 16 & 17 & 1990 & 2022\\
Chile & CHL & 2007 & 16 & 17 & 1990 & 2022\\
\addlinespace
Iran & IRN & 2007 & 13 & 17 & 1990 & 2019\\
Kazakhstan & KAZ & 2007 & 16 & 15 & 1992 & 2022\\
Congo - Kinshasa & COD & 2008 & 14 & 18 & 1990 & 2022\\
Japan & JPN & 2008 & 15 & 18 & 1990 & 2022\\
North Korea & PRK & 2008 & 12 & 13 & 1991 & 2019\\
\addlinespace
Thailand & THA & 2008 & 14 & 18 & 1990 & 2021\\
Australia & AUS & 2009 & 14 & 19 & 1990 & 2022\\
Brazil & BRA & 2009 & 14 & 19 & 1990 & 2022\\
Malaysia & MYS & 2009 & 14 & 19 & 1990 & 2022\\
South Africa & ZAF & 2009 & 14 & 15 & 1994 & 2022\\
\addlinespace
Peru & PER & 2010 & 13 & 20 & 1990 & 2022\\
Turkmenistan & TKM & 2010 & 13 & 18 & 1992 & 2022\\
Congo - Brazzaville & COG & 2011 & 12 & 18 & 1990 & 2022\\
Zimbabwe & ZWE & 2011 & 7 & 21 & 1990 & 2017\\
Russia & RUS & 2012 & 11 & 20 & 1992 & 2022\\
\addlinespace
Sierra Leone & SLE & 2012 & 11 & 22 & 1990 & 2022\\
New Zealand & NZL & 2013 & 10 & 23 & 1990 & 2022\\
Saudi Arabia & SAU & 2013 & 10 & 23 & 1990 & 2022\\
Uruguay & URY & 2013 & 10 & 23 & 1990 & 2022\\
Eritrea & ERI & 2014 & 9 & 21 & 1993 & 2022\\
\addlinespace
Myanmar (Burma) & MMR & 2014 & 9 & 24 & 1990 & 2022\\
Indonesia & IDN & 2016 & 7 & 25 & 1990 & 2022\\
Equatorial Guinea & GNQ & 2017 & 6 & 18 & 1995 & 2022\\
Gabon & GAB & 2017 & 6 & 27 & 1990 & 2022\\
Kuwait & KWT & 2018 & 5 & 28 & 1990 & 2022\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Ranks are computed from goods exports only. The restricted risk set keeps clean pre-entry non-China-top years and qualifying treated years for treated countries. Treatment year is the first retained year of a qualifying China-top goods-export period.
\end{tablenotes}
\end{threeparttable}}
\end{table}

\clearpage

\subsection*{Measurement Robustness: UNGA-DM Ideal Points}\label{measurement-robustness-unga-dm-ideal-points}
\addcontentsline{toc}{subsection}{Measurement Robustness: UNGA-DM Ideal Points}

The main estimations in the paper used the classic ideal-point measurement by BSV \citep{bailey_etal2017} as the response variable. However, according to \citet{fjelstul_etal2026}, the set of resolutions included in the BSV dataset is not complete. They provided a broader dataset, along with re-estimations of ideal points based on the new data. To assess whether the results of the paper change with this new measurement, I reran the main estimations with this new response variable. To make the comparison as close as possible, I held the treatment definition, donor and risk-set rules, covariate structure, and inference conventions fixed. The UNGA-DM series has a shorter time window, and the SDiD unit and time weights and the IFE factor count are re-estimated by their algorithms in response to the outcome series. These induced adjustments mean that the comparison evaluates the robustness of the analysis package to the alternative outcome; it is not a pure measurement-only perturbation of an otherwise identical fitted counterfactual. It is also important to note that 28 country-session rows had no ISO3c match and 0 SDiD rows had no outcome in the alternative measurement.

The two outcome measures preserve the negative direction of the Brazilian SDiD estimate, but they do not support a blanket claim of robustness across the Brazilian and cross-country designs. Table \ref{tab:ungadm-sdid-comparison} shows the comparison. Under UNGA-DM, the point estimate is nominally higher than the original in absolute terms (-0.331 versus -0.273), with a lower p-value of 0.008. The directional rank is the same in both measurements (3/96 (0.031)). The bilateral rank improves from 7/96 (0.073) to 5/96 (0.052). The pre-treatment means differ (0.647 under BSV versus 0.837 under UNGA-DM). But the effect measured as a percentage of the pre-treatment average is similar: -42.2 and -39.5 percent. The Brazilian result therefore retains its direction and inferential support under the alternative measure, with a similar relative magnitude. The cross-country comparison below is more sensitive to the outcome source: its IFE point estimate is closer to zero on the UNGA-DM scale and its uncertainty interval includes zero. The \(2\times2\) comparison below holds the common window and country-year panel fixed while varying the outcome source and factor count, allowing conditional factor-count comparisons within each measure. It does not provide a unique, scale-invariant decomposition of the difference between outcomes.

\begin{table}[H]
\centering
\caption{\label{tab:ungadm-sdid-comparison}Brazil SDiD under two sources of UNGA ideal points. Both columns use the same panel, the same donor pool, and the same placebo standard error settings; the outcome series is the only input that differs, and the synthetic-control weights are re-estimated from it.}
\centering
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lcc}
\toprule
  & Bailey, Strezhnev and Voeten & Fjelstul, Hug and Kilby\\
\midrule
ATT & -0.273 & -0.331\\
Placebo standard error & 0.131 & 0.125\\
95 percent confidence interval & {}[-0.529, -0.017] & {}[-0.576, -0.085]\\
p (normal approximation, two-sided) & 0.037 & 0.008\\
Directional placebo rank (p) & 3/96 (0.031) & 3/96 (0.031)\\
\addlinespace
Two-sided absolute placebo rank (p) & 7/96 (0.073) & 5/96 (0.052)\\
Intercept-adjusted pre-treatment RMSPE & 0.058 & 0.058\\
Brazil pre-treatment outcome mean & 0.647 & 0.837\\
ATT as percent of pre-treatment mean & -42.2 & -39.5\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Estimates are the post-2009 gap in absolute UNGA ideal-point distance to China, 1997-2015 annual panel, no covariates. Placebo SEs use 20,000 replications and seed 20260520 in both columns. Placebo-in-space ranks involve no random draws and are exactly reproducible.
\end{tablenotes}
\end{threeparttable}
\end{table}

Figure \ref{fig:ungadm-placebo-distribution} reports the placebo-in-space distribution for the UNGA-DM SDiD fit. It is close to the distribution obtained under the original outcome. The directional placebo rank is unchanged under the alternative measure (3/96 (0.031) in both columns), while the bilateral absolute rank improves from 7/96 (0.073) to 5/96 (0.052). Table \ref{tab:ungadm-sdid-comparison} reports this cross-measure comparison, and Table \ref{tab:ungadm-rank-criteria} reports the donor-exclusion checks under UNGA-DM.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:ungadm-placebo-distribution}Placebo-in-space distribution under the UNGA-DM outcome, with Brazil marked. Brazil's estimate is the 3rd most negative of 96 assignments (directional p = 0.031); the two-sided absolute rank is 5/96 (p = 0.052). Negative values indicate convergence toward China. Note: Estimated post-2009 gap in absolute UNGA ideal-point distance to China, UNGA-DM measure. Window: 1997-2015 annual SDiD panel.}]{/Users/manoelgaldino/Documents/DCP/Papers/RDD Trade/red_trade/output/submission/cpsr/raw/cpsr_full_inline_anonymous_files/figure-latex/ungadm-placebo-distribution-1.pdf}}
\caption{\label{fig:ungadm-placebo-distribution}Placebo-in-space distribution under the UNGA-DM outcome, with Brazil marked. Brazil's estimate is the 3rd most negative of 96 assignments (directional p = 0.031); the two-sided absolute rank is 5/96 (p = 0.052). Negative values indicate convergence toward China. Note: Estimated post-2009 gap in absolute UNGA ideal-point distance to China, UNGA-DM measure. Window: 1997-2015 annual SDiD panel.}
\end{figure}

\begin{table}[H]
\centering
\caption{\label{tab:ungadm-rank-criteria}Placebo rank inference under the UNGA-DM outcome, by donor-exclusion criterion.}
\centering
\fontsize{8}{10}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{5.4cm}lcc}
\toprule
Comparison set & Excluded donors & Directional rank (p) & Two-sided rank (p)\\
\midrule
All valid assignments & -- & 3/96 (0.031) & 5/96 (0.052)\\
Exclude goods-only China-top donor assignments (harmonized: window criterion) & -- & 3/96 (0.031) & 5/96 (0.052)\\
Exclude goods-only China-top donor assignments (legacy 5-year qualifying criterion; audit only) & GAB, KWT & 3/94 (0.032) & 5/94 (0.053)\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item The window criterion excludes donors observed as China-top in goods exports within 1997-2015, which is the criterion used elsewhere in the paper. The legacy criterion excludes countries that qualify under the five-year duration rule outside the analysis window, and is reported for audit only.
\end{tablenotes}
\end{threeparttable}
\end{table}

Donor weights are estimated separately for each fit, so they are not identical across outcomes. Table \ref{tab:ungadm-donor-weights} reports how much they change. Weight is spread among donors in a similar way in both fits: 0.044 under UNGA-DM and 0.031 under BSV. The correlation of the donor pool weights is moderate (0.462), but among the top ten donors, 6 are the same. The donor mix therefore shifts moderately across outcomes. For Brazil, the negative estimate and similar relative magnitude are preserved, but the two fits do not use identical counterfactual weights; this comparison does not establish stability of the cross-country result.

\begin{table}[H]
\centering
\caption{\label{tab:ungadm-donor-weights}Ten largest synthetic-control donor weights under the UNGA-DM fit, with the weight the same donor receives under the main outcome.}
\centering
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lcc}
\toprule
Donor & UNGA-DM weight & BSV weight\\
\midrule
COL & 0.044 & 0.022\\
IND & 0.031 & 0.021\\
SEN & 0.031 & 0.009\\
BRB & 0.029 & 0.015\\
GTM & 0.027 & 0.027\\
\addlinespace
GHA & 0.026 & 0.000\\
TTO & 0.026 & 0.015\\
PRY & 0.026 & 0.027\\
BOL & 0.025 & 0.023\\
SGP & 0.023 & 0.029\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Weights are normalized over the full donor pool of 95 units rather than over the displayed donors. The ten donors shown carry 28.8 percent of total weight under the UNGA-DM fit. Across all donors, the correlation between the two weight vectors is 0.462, and 6 of the ten largest donors are shared by the two fits.
\end{tablenotes}
\end{threeparttable}
\end{table}

Regarding the panel regression, Table \ref{tab:ungadm-ife-window} shows the IFE estimation in the same time window for both outcomes, and the original estimation with the larger time window. The estimate retains the negative sign but is closer to zero on the UNGA-DM scale, with an uncertainty interval that includes zero:
-0.027 with p =
0.573. However, the models are not the same, since the number of latent factors chosen by cross-validation is different: 2 under BSV and 1 under UNGA-DM. The \(2\times2\) comparison below holds the common window and country-year panel fixed while crossing the outcome source with one versus two latent factors, allowing sensitivity to factor count to be assessed within each outcome measure rather than uniquely decomposing the cross-outcome difference.

\begin{table}[H]
\centering
\caption{\label{tab:ungadm-ife-window}Cross-country interactive fixed-effects panel under the two outcome sources, in a common window with identical rows.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{5.2cm}cccccl}
\toprule
Specification & ATT & SE & 95 percent CI & p & Factors (CV) & Country-years\\
\midrule
BSV full window 1990-2022 (paper main, stored target) & -0.101 & 0.039 & {}[-0.177, -0.024] & 0.010 & 2 & 5,037\\
BSV common window (<= 2020, identical rows) & -0.095 & 0.040 & {}[-0.173, -0.018] & 0.016 & 2 & 4,727\\
UNGA-DM common window (<= 2020, identical rows) & -0.027 & 0.048 & {}[-0.120, 0.066] & 0.573 & 1 & 4,727\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item All rows use the goods-only status-current restricted risk set with 35 treated and 126 control countries. The common-window rows keep exactly the same country-years in both outcome sources. Confidence intervals come from 10,000 bootstrap replications. ATTs and intervals are expressed on each outcome's original scale; raw cross-outcome differences do not identify a scale-invariant measurement contribution.
\end{tablenotes}
\end{threeparttable}}
\end{table}

Table \ref{tab:ungadm-ife-2x2} holds the common window and country-year panel fixed and crosses the two outcome sources with one and two latent factors. This \(2\times2\) comparison describes sensitivity to factor count conditional on the outcome measure. Holding the outcome fixed, moving from one to two factors makes the ATT more negative (larger in absolute value): from -0.036 to -0.095 under BSV, and from -0.027 to -0.065 under UNGA-DM. Cross-validation selects 2 factors under BSV and 1 under UNGA-DM. The change from one to two factors differs across the two measures, indicating a descriptive interaction between outcome source and factor count rather than a unique additive decomposition. This comparison does not test the interaction. Both UNGA-DM fits have negative point estimates and uncertainty intervals that include zero; overlapping intervals do not establish equivalence. Holding the factor count at two still leaves a smaller UNGA-DM estimate (-0.065) than the BSV estimate (-0.095), but these raw estimates are expressed on different outcome scales. Their difference is a conditional sensitivity comparison, not a scale-invariant contribution attributable to outcome source.

\begin{table}[H]
\centering
\caption{\label{tab:ungadm-ife-2x2}Outcome source by number of latent factors, holding the panel fixed.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{9}{11}\selectfont
\begin{threeparttable}
\begin{tabular}[t]{lcccccc}
\toprule
Outcome & Factors (fixed) & Selected by CV & ATT & SE & 95 percent CI & p\\
\midrule
BSV & 1 & No & -0.036 & 0.037 & {}[-0.109, 0.037] & 0.336\\
UNGA-DM & 1 & Yes & -0.027 & 0.048 & {}[-0.120, 0.066] & 0.573\\
BSV & 2 & Yes & -0.095 & 0.040 & {}[-0.173, -0.018] & 0.016\\
UNGA-DM & 2 & No & -0.065 & 0.055 & {}[-0.172, 0.043] & 0.238\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Note: } 
\item Same common window and identical rows as the previous table. Paired bootstrap on UNGA-DM minus BSV in their original outcome units, 1,000 replications and no failures: 0.069 (percentile p = 0.134) with the original CV-selected counts held fixed (BSV: two; UNGA-DM: one), and 0.030 (percentile p = 0.356) with two factors for both outcomes. The same stratified country draws are used for both measures; factor counts are not reselected within replications. These are scale-dependent contrasts, not a unique decomposition of factor and outcome-source components. Non-rejection does not establish equivalence.
\end{tablenotes}
\end{threeparttable}}
\end{table}

To sum up, the Brazilian SDiD result retains its negative direction and inferential support across the two outcome measurements, with similar relative magnitude but a different absolute scale. The \(2\times2\) IFE comparison shows that two factors produce a more negative ATT under either outcome, with a different within-measure change under BSV and UNGA-DM. Both UNGA-DM fits have negative point estimates and uncertainty intervals that include zero; this does not establish equivalence between them. Even with two factors held fixed, the raw UNGA-DM estimate is closer to zero than the BSV estimate on its own scale. This conditional comparison does not isolate a scale-invariant outcome-source contribution beyond factor selection. The paired test does not detect a statistically significant difference between the ATTs, but this non-rejection does not establish equivalence and may reflect uncertainty.



\end{document}
