# Bounded read-only verification; no estimators or targets operations.
stopifnot(Sys.getenv("CODEX_AUTO_COMMIT_PUSH_DRY_RUN") == "1")
source("reports/refine_ink_review_paper_v4_2026-09-14/execution/domain_note_verify.R")
source("reports/refine_ink_review_paper_v4_2026-09-14/execution/comparability_verify.R")
d <- readRDS("_targets/objects/synth_data")
g <- readRDS("_targets/objects/gpi_data")
f <- readRDS("_targets/objects/synth_fit_no_time_varying_covariates")
a <- attr(f,"setup"); w <- attr(f,"weights")
stopifnot(identical(as.integer(dim(a$X)),c(96L,19L,0L)))
x <- merge(d[d$year<=2015,c("iso3c","year")],g[c("iso3c","year","gpi","us_power","us_power_gap")],by=c("iso3c","year"))
stopifnot(nrow(x)==1824, !anyDuplicated(x[c("iso3c","year")]), !anyNA(x),all(x$us_power>=x$gpi),max(abs(x$us_power_gap-(x$us_power-x$gpi)))==0)
cat("Item31: all 1824 fitting rows, 96 countries, 1997-2015 satisfy signed identity; main X=96x19x0.\n")
att <- as.numeric(t(c(-w$omega,1)) %*% a$Y %*% c(-w$lambda,rep(1/7,7)))
stopifnot(abs(att-as.numeric(f))<1e-12,abs(sum(w$omega)-1)<1e-12,abs(sum(w$lambda)-1)<1e-12)
m <- read.csv("data/processed/diagnostics/paper_v4_brazil_sdid_no_covariates/main_summary.csv")
s <- readRDS("_targets/objects/se_synth_no_time_varying_covariates")
stopifnot(abs(as.numeric(s)-m$se_placebo)<1e-12,abs(att-m$estimate)<1e-12,attr(s,"replications")==20000,abs(2*pnorm(-abs(att/s))-m$p_normal_two_sided)<1e-12)
p <- read.csv("data/processed/diagnostics/paper_v4_brazil_sdid_no_covariates/placebo_distribution.csv")
print(names(p));cat("ATT=",att," SE=",as.numeric(s)," Normal p=",m$p_normal_two_sided," rank=",m$rank_one_sided_negative,"/",m$rank_denominator," absolute=",m$rank_two_sided_absolute,"/",m$rank_denominator,"\n")
cat("PASS: all computations verification only.\n")

stopifnot(nrow(p)==96,sum(p$estimate<=att+1e-12)==3,sum(abs(p$estimate)>=abs(att)-1e-12)==7)
u <- readRDS("_targets/objects/unga_data")
print(u[u$iso3c %in% c("BRA","CHN") & u$year %in% 2005:2012,c("iso3c","year","ideal_point_all")])
Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
v <- read.csv("data/folha_validation_sample_annotated.csv", sep = ";", fileEncoding = "UTF-8")
print(names(v));cat("Validation rows",nrow(v),"\n")
c <- readRDS("data/folha_classificado.rds")
stopifnot(nrow(c)==14589,length(unique(c$title))==14589,all(c$model=="gpt-4.1-mini"))
cat("Final stored rank and corpus check PASS\n")

audit <- readRDS("data/processed/diagnostics/RIO_20260905_australia/australia_appendix_tables_patch.rds")
us <- readRDS("_targets/objects/china_top_m2_goods_status_current_unit_summary")
cur <- us$iso3c[us$min_duration_years==5 & us$sample=="risk_set_restricted" & us$ever_treated]
aids <- audit$tables$salience_country_matrix$iso3c
stopifnot(length(cur)==35,length(aids)==14,length(intersect(cur,aids))==13,length(setdiff(cur,aids))==22,identical(setdiff(aids,cur),"QAT"),nrow(audit$tables$recoverability_table)==9)
stopifnot(nrow(v)==100,mean(v$chatgpt_label==v$manual_label)==0.88)
cat("Item2 audit 35 current /14 archived /13 common /22 unaudited /QAT noncurrent /9 displayed: PASS\n")
cat("Item8 unweighted validation agreement 0.88: PASS\n")
